import type {
  BalanceWithdrawSnapshot,
  BoostCampaign,
  Coupon,
  Expense,
  FinancialSummary,
  GymSubscriptionSnapshot,
  MembershipPlan,
  Payment,
} from "@/lib/types";
import type { GymFinancialScreenProps } from "./gym-financial.screen";

export function createGymFinancialFixture(
  overrides: Partial<GymFinancialScreenProps> = {},
): GymFinancialScreenProps {
  return {
    financialSummary: {
      totalRevenue: 42850,
      totalExpenses: 12400,
      netProfit: 30450,
      monthlyRecurring: 38200,
      pendingPayments: 2500,
      overduePayments: 1200,
      averageTicket: 120,
      churnRate: 2,
      revenueGrowth: 15,
    } as FinancialSummary,
    payments: [
      {
        id: "payment-1",
        studentId: "student-1",
        studentName: "Ana Souza",
        planId: "plan-1",
        planName: "Plano Mensal",
        amount: 129.9,
        date: new Date(),
        dueDate: new Date(),
        status: "paid",
        paymentMethod: "pix",
      },
      {
        id: "payment-2",
        studentId: "student-2",
        studentName: "Marcos Lima",
        planId: "plan-1",
        planName: "Plano Mensal",
        amount: 129.9,
        date: new Date(Date.now() - 15 * 24 * 60 * 60 * 1000),
        dueDate: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000),
        status: "pending",
        paymentMethod: "credit-card",
      },
    ] as Payment[],
    coupons: [
      {
        id: "coupon-1",
        code: "PROMO20",
        type: "percentage",
        value: 20,
        maxUses: 100,
        currentUses: 24,
        expiryDate: new Date(Date.now() + 20 * 24 * 60 * 60 * 1000),
        isActive: true,
      },
    ] as Coupon[],
    campaigns: [
      {
        id: "campaign-1",
        gymId: "gym-profile-1",
        title: "Open Week",
        description: "Semana promocional para novas matrículas.",
        primaryColor: "#E2FF38",
        durationHours: 24,
        amountCents: 6000,
        status: "active",
        clicks: 37,
        impressions: 840,
        radiusKm: 5,
        linkedCouponId: "coupon-1",
        linkedPlanId: "plan-1",
        abacatePayBillingId: "billing-1",
        startsAt: new Date(),
        endsAt: new Date(Date.now() + 24 * 60 * 60 * 1000),
        createdAt: new Date(),
        updatedAt: new Date(),
      },
    ] as BoostCampaign[],
    plans: [
      {
        id: "plan-1",
        name: "Plano Mensal",
        type: "monthly",
        price: 129.9,
        duration: 30,
        benefits: ["Acesso livre", "Treino assistido"],
        isActive: true,
      },
    ] as MembershipPlan[],
    expenses: [
      {
        id: "expense-1",
        type: "rent",
        description: "Aluguel da unidade principal",
        amount: 4200,
        date: new Date(),
        category: "Infraestrutura",
      },
    ] as Expense[],
    balanceWithdraws: {
      balanceReais: 2450.75,
      balanceCents: 245075,
      withdraws: [
        {
          id: "withdraw-1",
          amount: 500,
          pixKey: "academia@gymrats.local",
          pixKeyType: "EMAIL",
          externalId: "pix-1",
          status: "completed",
          createdAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000),
          completedAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000),
        },
      ],
    } as BalanceWithdrawSnapshot,
    subscription: {
      id: "subscription-1",
      plan: "premium",
      status: "active",
      basePrice: 199,
      pricePerStudent: 2.5,
      pricePerPersonal: 0,
      currentPeriodStart: new Date("2026-03-01T00:00:00.000Z"),
      currentPeriodEnd: new Date("2026-04-01T00:00:00.000Z"),
      cancelAtPeriodEnd: false,
      canceledAt: null,
      trialStart: null,
      trialEnd: null,
      isTrial: false,
      daysRemaining: 7,
      activeStudents: 164,
      activePersonals: 0,
      totalAmount: 609,
      billingPeriod: "monthly",
    } as GymSubscriptionSnapshot,
    viewMode: "overview",
    onViewModeChange: () => undefined,
    ...overrides,
  };
}
