FROM oven/bun:1.3.6
WORKDIR /app

COPY . .
RUN bun install
RUN bun x prisma generate --schema packages/db/prisma/schema.prisma

ENV NODE_ENV=development
ENV HOST=0.0.0.0
ENV PORT=3000
ENV NEXT_TELEMETRY_DISABLED=1

CMD ["bun", "--version"]
