import type { ExerciseInfo } from "../types";

export const exerciseDatabase: ExerciseInfo[] = [
  {
    id: "bench-press",
    name: "Supino Reto",
    primaryMuscles: ["peito"],
    secondaryMuscles: ["ombros", "bracos"],
    difficulty: "intermediario",
    equipment: ["Barra", "Banco", "Anilhas"],
    instructions: [
      "Deite-se no banco com os pés apoiados no chão",
      "Pegue a barra com pegada ligeiramente mais larga que os ombros",
      "Desça a barra controladamente até tocar o peito",
      "Empurre a barra de volta à posição inicial",
      "Mantenha os omoplatas retraídos durante todo o movimento",
    ],
    tips: [
      "Mantenha os cotovelos a 45 graus do corpo, não 90 graus",
      "Crie um pequeno arco nas costas",
      "Empurre através da linha média do peito",
      "Respire fundo antes de descer, expire ao empurrar",
    ],
    commonMistakes: [
      "Bater a barra no peito sem controle",
      "Cotovelos muito abertos (90 graus)",
      "Tirar os glúteos do banco",
      "Não usar amplitude completa",
      "Movimentos assimétricos da barra",
    ],
    benefits: [
      "Desenvolvimento completo do peitoral",
      "Aumento de força do tronco superior",
      "Transferência para movimentos funcionais de empurrar",
      "Estímulo hormonal para crescimento muscular",
    ],
    scientificEvidence:
      "Estudos eletromiográficos mostram que o supino reto ativa significativamente as três porções do peitoral, com ênfase na porção esternocostal.",
  },
  {
    id: "squat",
    name: "Agachamento Livre",
    primaryMuscles: ["pernas", "gluteos"],
    secondaryMuscles: ["core", "costas"],
    difficulty: "intermediario",
    equipment: ["Barra", "Rack", "Anilhas"],
    instructions: [
      "Posicione a barra sobre o trapézio superior",
      "Pés na largura dos ombros, ligeiramente abertos",
      "Desça flexionando quadris e joelhos simultaneamente",
      "Mantenha o tronco ereto e joelhos alinhados com os pés",
      "Desça até quadris abaixo da linha dos joelhos",
      "Suba empurrando através dos calcanhares",
    ],
    tips: [
      "Mantenha o core contraído durante todo movimento",
      "Olhe ligeiramente para cima para manter coluna neutra",
      "Joelhos devem seguir a direção dos pés",
      "Inspire na descida, expire na subida",
    ],
    commonMistakes: [
      "Joelhos colapsando para dentro",
      "Calcanhar saindo do chão",
      "Tronco inclinando demais para frente",
      "Não atingir profundidade adequada",
      "Perder tensão no core",
    ],
    benefits: [
      "Desenvolvimento completo de membros inferiores",
      "Aumento de força funcional",
      "Estímulo à produção de hormônios anabólicos",
      "Melhora de mobilidade e estabilidade",
      "Fortalecimento do core",
    ],
    scientificEvidence:
      "Pesquisas demonstram que o agachamento profundo ativa mais fibras dos quadríceps e glúteos comparado ao agachamento parcial, além de ser seguro para joelhos saudáveis.",
  },
  {
    id: "deadlift",
    name: "Levantamento Terra",
    primaryMuscles: ["costas", "gluteos", "pernas"],
    secondaryMuscles: ["core", "bracos"],
    difficulty: "avancado",
    equipment: ["Barra", "Anilhas"],
    instructions: [
      "Posicione-se com pés sob a barra, na largura dos quadris",
      "Segure a barra com pegada pronada ou mista",
      "Mantenha coluna neutra, peito para cima",
      "Empurre o chão com os pés enquanto puxa a barra",
      "Estenda quadris e joelhos simultaneamente",
      "Finalize em posição ereta com ombros para trás",
    ],
    tips: [
      "A barra deve deslizar próxima ao corpo",
      "Ative o latíssimo para estabilizar a barra",
      "Pense em 'empurrar o chão' e não 'puxar a barra'",
      "Mantenha o core fortemente contraído",
    ],
    commonMistakes: [
      "Arredondar a coluna lombar",
      "Barra longe do corpo",
      "Puxar com os braços ao invés das pernas",
      "Hiperextensão na posição final",
      "Descer a barra sem controle",
    ],
    benefits: [
      "Exercício mais completo para corpo todo",
      "Desenvolvimento extremo de força posterior",
      "Fortalecimento de pegada",
      "Melhora de postura",
      "Alto gasto calórico",
    ],
    scientificEvidence:
      "Considerado o exercício com maior ativação muscular total, recrutando mais de 200 músculos simultaneamente segundo análises biomecânicas.",
  },
  {
    id: "pull-up",
    name: "Barra Fixa",
    primaryMuscles: ["costas"],
    secondaryMuscles: ["bracos", "ombros", "core"],
    difficulty: "intermediario",
    equipment: ["Barra fixa"],
    instructions: [
      "Segure a barra com pegada pronada (palmas para frente)",
      "Mãos ligeiramente mais largas que os ombros",
      "Puxe os cotovelos para baixo e para trás",
      "Eleve o corpo até queixo passar a barra",
      "Desça controladamente até extensão completa",
    ],
    tips: [
      "Inicie o movimento retraindo as escápulas",
      "Pense em puxar os cotovelos, não as mãos",
      "Mantenha o core ativo para evitar balanço",
      "Use pegada completa (polegar envolvendo a barra)",
    ],
    commonMistakes: [
      "Usar impulso do corpo (kipping)",
      "Não usar amplitude completa",
      "Projetar os ombros para frente",
      "Elevar apenas usando bíceps",
      "Não controlar a descida",
    ],
    benefits: [
      "Desenvolvimento completo das costas",
      "Melhora de força relativa",
      "Fortalecimento de pegada",
      "Desenvolvimento funcional",
      "Versatilidade (várias variações)",
    ],
    scientificEvidence:
      "EMG mostra que a barra fixa ativa significativamente mais o grande dorsal comparado a máquinas de pulldown, especialmente na fase excêntrica.",
  },
  {
    id: "tricep-extension",
    name: "Tríceps Testa",
    primaryMuscles: ["bracos"],
    secondaryMuscles: ["ombros"],
    difficulty: "iniciante",
    equipment: ["Barra", "Banco", "Anilhas"],
    instructions: [
      "Deite-se no banco com os pés no chão",
      "Segure a barra com pegada fechada",
      "Posicione a barra acima da cabeça com braços estendidos",
      "Flexione os cotovelos e desça a barra em direção à testa",
      "Estenda os braços até voltar à posição inicial",
    ],
    tips: [
      "Mantenha os cotovelos fixos, apontando para cima",
      "Não abra os cotovelos durante o movimento",
      "Controle a fase excêntrica",
      "Mantenha o core ativo",
    ],
    commonMistakes: [
      "Abrir os cotovelos durante o movimento",
      "Usar peso excessivo comprometendo a forma",
      "Arquear excessivamente as costas",
      "Não usar amplitude completa",
    ],
    benefits: [
      "Desenvolvimento isolado do tríceps",
      "Ativa todas as três cabeças",
      "Melhora força de extensão",
      "Aumento do volume do braço",
    ],
    scientificEvidence:
      "Estudos EMG mostram alta ativação das três cabeças do tríceps, especialmente a cabeça longa.",
  },
  {
    id: "tricep-pushdown",
    name: "Tríceps Pulley",
    primaryMuscles: ["bracos"],
    secondaryMuscles: [],
    difficulty: "iniciante",
    equipment: ["Cabo", "Polia"],
    instructions: [
      "Posicione-se frente à polia alta",
      "Segure a barra com pegada pronada",
      "Mantenha cotovelos junto ao corpo",
      "Estenda os braços completamente para baixo",
      "Retorne controladamente à posição inicial",
    ],
    tips: [
      "Mantenha os cotovelos fixos junto ao corpo",
      "Não balance o corpo para ajudar",
      "Use pegada em V para maior ativação",
      "Sinta a contração no tríceps",
    ],
    commonMistakes: [
      "Abrir os cotovelos",
      "Usar impulso do corpo",
      "Não estender completamente",
      "Inclinar o tronco para frente",
    ],
    benefits: [
      "Isolamento efetivo do tríceps",
      "Técnica relativamente simples",
      "Permite altas repetições",
      "Menor estresse articular",
    ],
    scientificEvidence:
      "Exercício isolador efetivo para tríceps com baixa ativação de músculos secundários.",
  },
  {
    id: "dips",
    name: "Paralelas",
    primaryMuscles: ["bracos"],
    secondaryMuscles: ["peito", "ombros"],
    difficulty: "intermediario",
    equipment: ["Barras paralelas"],
    instructions: [
      "Segure nas barras paralelas com braços estendidos",
      "Incline ligeiramente o tronco para frente",
      "Desça flexionando os cotovelos",
      "Desça até ombros ficarem abaixo dos cotovelos",
      "Empurre de volta à posição inicial",
    ],
    tips: [
      "Mantenha o core contraído",
      "Controle a descida",
      "Não deixe os ombros rodarem para frente",
      "Use assistência se necessário",
    ],
    commonMistakes: [
      "Não descer o suficiente",
      "Inclinar muito para frente (ativa mais peito)",
      "Deixar ombros caírem para frente",
      "Usar impulso",
    ],
    benefits: [
      "Exercício composto para tríceps e peito",
      "Desenvolvimento de força relativa",
      "Funcional e transferível",
      "Não requer equipamento adicional",
    ],
    scientificEvidence:
      "Exercício composto que ativa significativamente tríceps, peitoral e deltoide anterior.",
  },
  {
    id: "barbell-shrug",
    name: "Encolhimento com Barra",
    primaryMuscles: ["costas"],
    secondaryMuscles: [],
    difficulty: "iniciante",
    equipment: ["Barra", "Anilhas"],
    instructions: [
      "Fique em pé segurando a barra com pegada pronada",
      "Mantenha os braços estendidos",
      "Eleve os ombros o máximo possível",
      "Mantenha a contração por 1-2 segundos",
      "Desça controladamente",
    ],
    tips: [
      "Não gire os ombros (movimento apenas para cima)",
      "Use peso adequado para amplitude completa",
      "Mantenha o tronco ereto",
      "Não flexione os cotovelos",
    ],
    commonMistakes: [
      "Rotacionar os ombros",
      "Usar peso excessivo reduzindo amplitude",
      "Flexionar os cotovelos",
      "Arquear as costas",
    ],
    benefits: [
      "Desenvolvimento direto do trapézio superior",
      "Melhora da postura",
      "Fortalecimento para levantamento terra",
      "Exercício isolado efetivo",
    ],
    scientificEvidence:
      "EMG mostra alta ativação do trapézio superior, especialmente na parte medial.",
  },
  {
    id: "upright-row",
    name: "Remada Alta",
    primaryMuscles: ["ombros", "costas"],
    secondaryMuscles: ["bracos"],
    difficulty: "intermediario",
    equipment: ["Barra", "Anilhas"],
    instructions: [
      "Fique em pé segurando a barra com pegada fechada",
      "Puxe a barra verticalmente até a altura do peito",
      "Mantenha os cotovelos acima dos punhos",
      "Contraia o trapézio no topo",
      "Desça controladamente",
    ],
    tips: [
      "Não eleve acima da altura do peito",
      "Mantenha os cotovelos altos",
      "Controle o movimento em ambas as fases",
      "Evite balançar o corpo",
    ],
    commonMistakes: [
      "Elevar demais (pode causar impingimento)",
      "Usar pegada muito larga",
      "Balançar o corpo",
      "Puxar com os braços ao invés das costas",
    ],
    benefits: [
      "Desenvolvimento do trapézio médio e deltoides",
      "Melhora da força de puxar vertical",
      "Exercício composto efetivo",
      "Aumenta largura dos ombros",
    ],
    scientificEvidence:
      "Ativa trapézio médio e deltoides, mas cuidado com impingimento em elevadas altas.",
  },
  {
    id: "face-pull",
    name: "Face Pull",
    primaryMuscles: ["costas", "ombros"],
    secondaryMuscles: ["bracos"],
    difficulty: "iniciante",
    equipment: ["Cabo", "Polia"],
    instructions: [
      "Ajuste a polia na altura dos olhos",
      "Segure a corda com pegada neutra",
      "Puxe em direção ao rosto separando as cordas",
      "Contraia o trapézio médio e posterior",
      "Retorne controladamente",
    ],
    tips: [
      "Puxe para os lados do rosto, não para o centro",
      "Retraia as escápulas durante o movimento",
      "Mantenha o tronco ereto",
      "Use peso moderado para técnica correta",
    ],
    commonMistakes: [
      "Puxar para o centro do rosto",
      "Não retrair as escápulas",
      "Usar peso excessivo",
      "Arquear as costas",
    ],
    benefits: [
      "Desenvolvimento do deltoide posterior",
      "Fortalecimento dos romboides e trapézio médio",
      "Corrige desequilíbrios posturais",
      "Previne lesões no ombro",
    ],
    scientificEvidence:
      "Excelente para manguito rotador e deltoide posterior, músculos frequentemente negligenciados.",
  },
  {
    id: "hyperextension",
    name: "Hiperextensão Lombar",
    primaryMuscles: ["costas"],
    secondaryMuscles: ["gluteos"],
    difficulty: "iniciante",
    equipment: ["Banco de hiperextensão"],
    instructions: [
      "Posicione-se no banco com quadril apoiado",
      "Cruze os braços no peito ou atrás da cabeça",
      "Desça o tronco controladamente",
      "Estenda o tronco até alinhamento com as pernas",
      "Contraia os eretores da espinha",
    ],
    tips: [
      "Não hiperestender excessivamente",
      "Mantenha o movimento controlado",
      "Foque em contrair os lombares",
      "Não use impulso",
    ],
    commonMistakes: [
      "Hiperestender demais na posição final",
      "Usar impulso",
      "Focar em amplitude excessiva",
      "Não controlar a descida",
    ],
    benefits: [
      "Fortalecimento dos eretores da espinha",
      "Melhora da postura",
      "Prevenção de lesões lombares",
      "Auxilia em levantamento terra e agachamento",
    ],
    scientificEvidence:
      "Exercício isolado efetivo para eretores da espinha, crucial para saúde lombar.",
  },
  {
    id: "good-morning",
    name: "Boa Manhã",
    primaryMuscles: ["costas", "gluteos"],
    secondaryMuscles: ["pernas"],
    difficulty: "avancado",
    equipment: ["Barra", "Anilhas"],
    instructions: [
      "Posicione a barra sobre os trapézios",
      "Pés na largura dos quadris",
      "Flexione os quadris mantendo pernas retas",
      "Incline o tronco até paralelo ao chão",
      "Retorne à posição ereta contraindo os glúteos",
    ],
    tips: [
      "Mantenha coluna neutra durante todo movimento",
      "Foque em dobrar pelos quadris",
      "Use peso conservador inicialmente",
      "Contraia os glúteos para retornar",
    ],
    commonMistakes: [
      "Arredondar as costas",
      "Flexionar os joelhos demais",
      "Usar peso excessivo",
      "Não manter coluna neutra",
    ],
    benefits: [
      "Fortalecimento posterior completo",
      "Desenvolvimento de força dos eretores",
      "Melhora de padrão de dobradiça de quadril",
      "Transferência para levantamento terra",
    ],
    scientificEvidence:
      "Exercício de cadeia posterior que desenvolve força funcional e previne lesões.",
  },
  {
    id: "side-plank",
    name: "Prancha Lateral",
    primaryMuscles: ["core"],
    secondaryMuscles: ["ombros"],
    difficulty: "intermediario",
    equipment: [],
    instructions: [
      "Deite-se de lado apoiado no antebraço",
      "Estenda as pernas com pés empilhados",
      "Eleve o quadril do chão",
      "Mantenha corpo em linha reta",
      "Segure a posição",
    ],
    tips: [
      "Mantenha o corpo em linha reta",
      "Não deixe o quadril cair",
      "Respire normalmente",
      "Ative o core e oblíquos",
    ],
    commonMistakes: [
      "Deixar o quadril cair",
      "Arquear o corpo",
      "Colocar muito peso no braço",
      "Não ativar os oblíquos",
    ],
    benefits: [
      "Fortalecimento dos oblíquos",
      "Estabilização lateral do core",
      "Melhora da postura",
      "Prevenção de lesões",
    ],
    scientificEvidence:
      "Alta ativação do oblíquo externo e interno, essencial para estabilidade lateral.",
  },
  {
    id: "russian-twist",
    name: "Russian Twist",
    primaryMuscles: ["core"],
    secondaryMuscles: [],
    difficulty: "intermediario",
    equipment: ["Peso opcional"],
    instructions: [
      "Sente-se no chão com joelhos flexionados",
      "Incline o tronco para trás mantendo costas retas",
      "Eleve os pés do chão",
      "Rode o tronco de um lado para o outro",
      "Mantenha o core contraído",
    ],
    tips: [
      "Mantenha o tronco inclinado mas reto",
      "Controle o movimento",
      "Não balance o peso rapidamente",
      "Foque na contração dos oblíquos",
    ],
    commonMistakes: [
      "Arredondar as costas",
      "Balancer muito rápido",
      "Não manter os pés elevados",
      "Usar impulso",
    ],
    benefits: [
      "Desenvolvimento dos oblíquos",
      "Melhora da rotação do tronco",
      "Fortalecimento do core",
      "Exercício funcional",
    ],
    scientificEvidence:
      "Alta ativação dos oblíquos e reto abdominal durante rotação do tronco.",
  },
  {
    id: "cable-woodchop",
    name: "Cable Woodchop",
    primaryMuscles: ["core"],
    secondaryMuscles: ["ombros"],
    difficulty: "intermediario",
    equipment: ["Cabo", "Polia"],
    instructions: [
      "Ajuste a polia na altura máxima",
      "Segure o cabo com ambas as mãos",
      "Rode o tronco puxando diagonalmente",
      "Termine com o cabo na altura do quadril oposto",
      "Retorne controladamente",
    ],
    tips: [
      "Mantenha os braços relativamente retos",
      "Rode pelo tronco, não pelos braços",
      "Mantenha os pés plantados",
      "Controle ambas as fases",
    ],
    commonMistakes: [
      "Usar apenas os braços",
      "Não rotacionar o tronco",
      "Perder estabilidade",
      "Movimento muito rápido",
    ],
    benefits: [
      "Desenvolvimento funcional dos oblíquos",
      "Melhora de rotação e força",
      "Exercício anti-rotação",
      "Transferência para esportes",
    ],
    scientificEvidence:
      "Exercício funcional que desenvolve força rotacional, importante para atividades diárias e esportes.",
  },
  {
    id: "hip-thrust",
    name: "Hip Thrust",
    primaryMuscles: ["gluteos"],
    secondaryMuscles: ["pernas", "costas"],
    difficulty: "intermediario",
    equipment: ["Barra", "Banco", "Anilhas"],
    instructions: [
      "Apoie as costas no banco com omoplatas",
      "Posicione a barra sobre os quadris",
      "Pés no chão, joelhos a 90 graus",
      "Eleve os quadris até formar linha reta",
      "Contraia os glúteos no topo",
    ],
    tips: [
      "Mantenha o queixo próximo ao peito",
      "Contraia os glúteos antes de subir",
      "Não hiperestender na posição final",
      "Empurre através dos calcanhares",
    ],
    commonMistakes: [
      "Hiperestender a coluna",
      "Não contrair os glúteos",
      "Joelhos muito à frente",
      "Movimento muito curto",
    ],
    benefits: [
      "Desenvolvimento máximo dos glúteos",
      "Melhora de força do quadril",
      "Corrige desequilíbrios",
      "Alto estímulo muscular",
    ],
    scientificEvidence:
      "EMG mostra maior ativação do glúteo máximo comparado a agachamento e levantamento terra.",
  },
  {
    id: "glute-bridge",
    name: "Ponte de Glúteo",
    primaryMuscles: ["gluteos"],
    secondaryMuscles: ["pernas"],
    difficulty: "iniciante",
    equipment: [],
    instructions: [
      "Deite-se de costas com joelhos flexionados",
      "Pés no chão na largura dos quadris",
      "Eleve os quadris contraindo os glúteos",
      "Mantenha a contração no topo",
      "Desça controladamente",
    ],
    tips: [
      "Foque em contrair os glúteos",
      "Não arquear excessivamente as costas",
      "Mantenha o core ativo",
      "Pode adicionar peso para progressão",
    ],
    commonMistakes: [
      "Arquear demais as costas",
      "Não contrair os glúteos",
      "Usar os quadríceps em vez dos glúteos",
      "Movimento muito rápido",
    ],
    benefits: [
      "Ativação efetiva dos glúteos",
      "Exercício acessível sem equipamento",
      "Melhora de ativação glútea",
      "Auxilia em outros exercícios",
    ],
    scientificEvidence:
      "Exercício de ativação glútea efetivo, especialmente útil para pessoas com glúteos inativos.",
  },
  {
    id: "lateral-leg-raise",
    name: "Elevação Lateral de Perna",
    primaryMuscles: ["gluteos"],
    secondaryMuscles: [],
    difficulty: "iniciante",
    equipment: [],
    instructions: [
      "Deite-se de lado apoiado no antebraço",
      "Mantenha pernas estendidas e empilhadas",
      "Eleve a perna superior o máximo possível",
      "Mantenha a perna reta",
      "Desça controladamente",
    ],
    tips: [
      "Foque em elevar pelo quadril, não pela perna",
      "Mantenha o tronco estável",
      "Não balance a perna",
      "Sinta a contração no glúteo médio",
    ],
    commonMistakes: [
      "Girar o corpo para ajudar",
      "Elevar muito rápido",
      "Não manter a perna reta",
      "Não sentir contração no glúteo",
    ],
    benefits: [
      "Isolamento do glúteo médio",
      "Melhora de estabilidade do quadril",
      "Prevenção de lesões no joelho",
      "Corrige desequilíbrios",
    ],
    scientificEvidence:
      "Exercício isolado efetivo para glúteo médio, crucial para estabilidade do quadril e prevenção de lesões.",
  },
  {
    id: "leg-curl",
    name: "Mesa Flexora",
    primaryMuscles: ["pernas"],
    secondaryMuscles: [],
    difficulty: "iniciante",
    equipment: ["Máquina de leg curl"],
    instructions: [
      "Deite-se na máquina com as pernas sob o apoio",
      "Ajuste o apoio para ficar acima dos calcanhares",
      "Flexione os joelhos trazendo os calcanhares aos glúteos",
      "Contraia os isquiotibiais no topo",
      "Estenda controladamente",
    ],
    tips: [
      "Mantenha os quadris no banco",
      "Controle a fase excêntrica",
      "Não use impulso",
      "Foque em contrair os isquiotibiais",
    ],
    commonMistakes: [
      "Elevar os quadris do banco",
      "Usar peso excessivo",
      "Não controlar a descida",
      "Não usar amplitude completa",
    ],
    benefits: [
      "Isolamento efetivo dos isquiotibiais",
      "Desenvolvimento de força de flexão",
      "Balanceamento com quadríceps",
      "Prevenção de lesões",
    ],
    scientificEvidence:
      "EMG mostra alta ativação dos três músculos isquiotibiais durante flexão do joelho.",
  },
  {
    id: "nordic-curl",
    name: "Nordic Curl",
    primaryMuscles: ["pernas"],
    secondaryMuscles: ["gluteos", "core"],
    difficulty: "avancado",
    equipment: ["Parceiro ou apoio"],
    instructions: [
      "Ajoelhe-se no chão com os calcanhares fixos",
      "Mantenha o corpo reto",
      "Desça controladamente deixando o corpo inclinar",
      "Quando não conseguir mais, empurre de volta",
      "Ou use as mãos para assistir na subida",
    ],
    tips: [
      "Comece com movimento assistido",
      "Foque em controlar a descida",
      "Mantenha o core ativo",
      "Progressão gradual é essencial",
    ],
    commonMistakes: [
      "Descer muito rápido",
      "Não controlar o movimento",
      "Arredondar as costas",
      "Tentar fazer sem preparação",
    ],
    benefits: [
      "Fortalecimento excêntrico dos isquiotibiais",
      "Prevenção de lesões",
      "Exercício de peso corporal desafiador",
      "Melhora de força funcional",
    ],
    scientificEvidence:
      "Exercício excêntrico altamente efetivo para isquiotibiais, importante para prevenção de lesões.",
  },
  {
    id: "romanian-deadlift",
    name: "Stiff (RDL)",
    primaryMuscles: ["pernas", "gluteos"],
    secondaryMuscles: ["costas"],
    difficulty: "intermediario",
    equipment: ["Barra", "Anilhas"],
    instructions: [
      "Segure a barra com pegada pronada",
      "Pés na largura dos quadris",
      "Flexione levemente os joelhos",
      "Dobre pelos quadris mantendo costas retas",
      "Desça a barra até sentir alongamento nos isquiotibiais",
      "Retorne contraindo os glúteos",
    ],
    tips: [
      "Mantenha a barra próxima ao corpo",
      "Foque em dobrar pelos quadris",
      "Mantenha joelhos levemente flexionados",
      "Sinta o alongamento nos isquiotibiais",
    ],
    commonMistakes: [
      "Flexionar demais os joelhos",
      "Arredondar as costas",
      "Barra longe do corpo",
      "Não sentir alongamento",
    ],
    benefits: [
      "Desenvolvimento de isquiotibiais e glúteos",
      "Melhora de mobilidade do quadril",
      "Força da cadeia posterior",
      "Transferência funcional",
    ],
    scientificEvidence:
      "Exercício da cadeia posterior que desenvolve isquiotibiais e glúteos com alta ativação EMG.",
  },
  {
    id: "standing-calf-raise",
    name: "Panturrilha em Pé",
    primaryMuscles: ["pernas"],
    secondaryMuscles: [],
    difficulty: "iniciante",
    equipment: ["Máquina de panturrilha ou step"],
    instructions: [
      "Posicione os pés na máquina ou step",
      "Mantenha joelhos estendidos",
      "Eleve os calcanhares o máximo possível",
      "Contraia as panturrilhas no topo",
      "Desça até sentir alongamento completo",
    ],
    tips: [
      "Use amplitude completa de movimento",
      "Não balance o corpo",
      "Mantenha os joelhos estendidos",
      "Controle ambas as fases",
    ],
    commonMistakes: [
      "Não usar amplitude completa",
      "Balancear o corpo",
      "Flexionar os joelhos",
      "Movimento muito rápido",
    ],
    benefits: [
      "Desenvolvimento do gastrocnêmio",
      "Melhora de força de flexão plantar",
      "Estética das pernas",
      "Desempenho em saltos",
    ],
    scientificEvidence:
      "Ativa principalmente o gastrocnêmio devido à extensão do joelho, ideal para desenvolvimento da panturrilha superior.",
  },
  {
    id: "seated-calf-raise",
    name: "Panturrilha Sentado",
    primaryMuscles: ["pernas"],
    secondaryMuscles: [],
    difficulty: "iniciante",
    equipment: ["Máquina de panturrilha sentado"],
    instructions: [
      "Sente-se na máquina com joelhos flexionados a 90 graus",
      "Posicione as coxas sob o apoio",
      "Eleve os calcanhares o máximo possível",
      "Contraia as panturrilhas",
      "Desça até alongamento completo",
    ],
    tips: [
      "Use amplitude completa",
      "Foque no sóleo (panturrilha inferior)",
      "Mantenha os joelhos flexionados",
      "Controle o movimento",
    ],
    commonMistakes: [
      "Não usar amplitude completa",
      "Estender os joelhos",
      "Não sentir contração",
      "Usar peso excessivo",
    ],
    benefits: [
      "Desenvolvimento do sóleo",
      "Completa o desenvolvimento da panturrilha",
      "Trabalha com joelho flexionado",
      "Aumenta espessura da panturrilha",
    ],
    scientificEvidence:
      "Com joelho flexionado, ativa principalmente o sóleo, completando o desenvolvimento da panturrilha.",
  },
  {
    id: "wrist-curl",
    name: "Rosca de Punho",
    primaryMuscles: ["bracos"],
    secondaryMuscles: [],
    difficulty: "iniciante",
    equipment: ["Barra ou halteres"],
    instructions: [
      "Sente-se segurando a barra com pegada supinada",
      "Apoie os antebraços no banco",
      "Punhos devem ficar além da borda",
      "Flexione os punhos elevando a barra",
      "Desça controladamente até alongamento completo",
    ],
    tips: [
      "Use amplitude completa",
      "Mantenha os antebraços apoiados",
      "Controle o movimento",
      "Não balance",
    ],
    commonMistakes: [
      "Não usar amplitude completa",
      "Balancear os antebraços",
      "Usar peso excessivo",
      "Movimento muito rápido",
    ],
    benefits: [
      "Fortalecimento dos flexores do punho",
      "Melhora de força de pegada",
      "Prevenção de lesões",
      "Desenvolvimento estético",
    ],
    scientificEvidence:
      "Exercício isolado para flexores do punho, importante para força de pegada e prevenção de lesões.",
  },
  {
    id: "push-up",
    name: "Flexão de Braço",
    primaryMuscles: ["peito"],
    secondaryMuscles: ["ombros", "bracos", "core"],
    difficulty: "iniciante",
    equipment: [],
    instructions: [
      "Posicione-se em prancha alta",
      "Mãos na largura dos ombros",
      "Mantenha corpo em linha reta",
      "Desça o corpo até quase tocar o chão",
      "Empurre de volta à posição inicial",
    ],
    tips: [
      "Mantenha o core contraído",
      "Não deixe o quadril cair",
      "Controle ambas as fases",
      "Mantenha cotovelos a 45 graus",
    ],
    commonMistakes: [
      "Arquear as costas",
      "Deixar o quadril cair",
      "Não descer o suficiente",
      "Cotovelos muito abertos",
    ],
    benefits: [
      "Exercício composto completo",
      "Desenvolve peito, ombros e tríceps",
      "Fortalece o core",
      "Não requer equipamento",
    ],
    scientificEvidence:
      "Exercício composto que ativa peitoral, deltoide anterior e tríceps, além do core para estabilização.",
  },
  {
    id: "incline-bench-press",
    name: "Supino Inclinado",
    primaryMuscles: ["peito"],
    secondaryMuscles: ["ombros", "bracos"],
    difficulty: "intermediario",
    equipment: ["Banco inclinado", "Barra", "Anilhas"],
    instructions: [
      "Ajuste o banco a 30-45 graus",
      "Deite-se mantendo pés no chão",
      "Pegue a barra com pegada ligeiramente mais larga que ombros",
      "Desça controladamente até tocar o peito superior",
      "Empurre de volta à posição inicial",
    ],
    tips: [
      "Angulação de 30-45 graus é ideal",
      "Mantenha omoplatas retraídas",
      "Empurre através da parte superior do peito",
      "Controle a fase excêntrica",
    ],
    commonMistakes: [
      "Angulação muito alta (ativa mais ombros)",
      "Bater a barra no peito",
      "Tirar glúteos do banco",
      "Não usar amplitude completa",
    ],
    benefits: [
      "Desenvolvimento do peitoral superior",
      "Aumenta largura do tórax",
      "Melhora força de empurrar",
      "Balanceamento com peito inferior",
    ],
    scientificEvidence:
      "EMG mostra maior ativação da cabeça clavicular do peitoral comparado ao supino reto.",
  },
  {
    id: "cable-fly",
    name: "Crucifixo no Cabo",
    primaryMuscles: ["peito"],
    secondaryMuscles: ["ombros"],
    difficulty: "iniciante",
    equipment: ["Cabos", "Polias"],
    instructions: [
      "Ajuste as polias na altura dos ombros",
      "Fique no centro segurando os cabos",
      "Brace o core e leve os braços para frente",
      "Junte as mãos à frente do peito",
      "Retorne controladamente sentindo alongamento",
    ],
    tips: [
      "Mantenha leve flexão nos cotovelos",
      "Foque no peitoral, não nos ombros",
      "Controle o alongamento na volta",
      "Não balance o corpo",
    ],
    commonMistakes: [
      "Estender demais os cotovelos",
      "Usar peso excessivo",
      "Balancear o corpo",
      "Não sentir alongamento",
    ],
    benefits: [
      "Isolamento efetivo do peitoral",
      "Alongamento e contração completos",
      "Desenvolvimento da largura do peito",
      "Menor estresse articular",
    ],
    scientificEvidence:
      "Exercício de isolamento que proporciona alongamento e contração máximos do peitoral.",
  },
  // ============================================
  // EXERCÍCIOS ADICIONAIS - PEITO
  // ============================================
  {
    id: "bench-press-incline",
    name: "Supino Inclinado",
    primaryMuscles: ["peito"],
    secondaryMuscles: ["ombros", "bracos"],
    difficulty: "intermediario",
    equipment: ["Banco Inclinado", "Barra", "Anilhas"],
    instructions: [
      "Ajuste o banco em 30-45 graus de inclinação",
      "Deite-se com os pés firmes no chão",
      "Pegue a barra com pegada ligeiramente mais larga que os ombros",
      "Desça a barra até o peito superior",
      "Empurre a barra de volta à posição inicial",
    ],
    tips: [
      "A inclinação de 30-45 graus ativa mais a porção superior do peitoral",
      "Mantenha os omoplatas retraídos",
      "Não arquear excessivamente as costas",
      "Controle a descida da barra",
    ],
    commonMistakes: [
      "Inclinação muito alta (trabalha mais ombros que peito)",
      "Não usar amplitude completa",
      "Pés no banco (reduz estabilidade)",
      "Barra muito alta no peito",
    ],
    benefits: [
      "Desenvolvimento da porção superior do peitoral",
      "Melhora da definição do peito",
      "Aumento de força funcional",
      "Estética superior do tórax",
    ],
    scientificEvidence:
      "EMG mostra que inclinações de 30-45 graus maximizam a ativação da porção clavicular do peitoral maior.",
  },
  {
    id: "bench-press-decline",
    name: "Supino Declinado",
    primaryMuscles: ["peito"],
    secondaryMuscles: ["ombros", "bracos"],
    difficulty: "intermediario",
    equipment: ["Banco Declinado", "Barra", "Anilhas"],
    instructions: [
      "Ajuste o banco em declive de 15-30 graus",
      "Prenda os pés nas alças de segurança",
      "Pegue a barra com pegada ligeiramente mais larga que os ombros",
      "Desça a barra até o peito inferior",
      "Empurre a barra de volta à posição inicial",
    ],
    tips: [
      "A declinação trabalha mais a porção inferior do peitoral",
      "Mantenha os pés sempre presos",
      "Controle total do movimento",
      "Não use peso excessivo",
    ],
    commonMistakes: [
      "Declinação muito acentuada (perigoso)",
      "Pés soltos (risco de queda)",
      "Barra muito baixa no peito",
      "Não usar segurança",
    ],
    benefits: [
      "Desenvolvimento da porção inferior do peitoral",
      "Maior ativação da porção esternocostal",
      "Força funcional para movimentos de empurrar para baixo",
    ],
    scientificEvidence:
      "Estudos mostram maior ativação da porção inferior do peitoral em declinações de 15-30 graus.",
  },
  {
    id: "dumbbell-bench-press",
    name: "Supino com Halteres",
    primaryMuscles: ["peito"],
    secondaryMuscles: ["ombros", "bracos"],
    difficulty: "intermediario",
    equipment: ["Halteres", "Banco"],
    instructions: [
      "Deite-se no banco segurando halteres",
      "Posicione os halteres ao lado do peito com cotovelos a 45 graus",
      "Empurre os halteres para cima até quase tocar",
      "Desça controladamente até alongamento completo",
      "Mantenha os halteres alinhados",
    ],
    tips: [
      "Maior amplitude de movimento que com barra",
      "Permite movimento mais natural dos ombros",
      "Trabalha estabilizadores",
      "Pode corrigir assimetrias",
    ],
    commonMistakes: [
      "Halteres desalinhados",
      "Amplitude incompleta",
      "Peso excessivo comprometendo forma",
      "Não controlar a descida",
    ],
    benefits: [
      "Maior amplitude de movimento",
      "Desenvolvimento de estabilidade",
      "Correção de assimetrias",
      "Menor estresse nos ombros",
    ],
    scientificEvidence:
      "Halteres permitem maior amplitude e ativação do peitoral comparado à barra, além de maior ativação dos estabilizadores.",
  },
  {
    id: "dumbbell-fly",
    name: "Crucifixo com Halteres",
    primaryMuscles: ["peito"],
    secondaryMuscles: ["ombros"],
    difficulty: "iniciante",
    equipment: ["Halteres", "Banco"],
    instructions: [
      "Deite-se no banco segurando halteres",
      "Braços ligeiramente flexionados",
      "Abra os braços em arco até sentir alongamento",
      "Feche os braços como se estivesse abraçando",
      "Mantenha leve flexão nos cotovelos",
    ],
    tips: [
      "Foque no alongamento e contração",
      "Não estenda completamente os cotovelos",
      "Movimento controlado e lento",
      "Sinta o peitoral trabalhando",
    ],
    commonMistakes: [
      "Estender demais os cotovelos",
      "Peso excessivo",
      "Movimento muito rápido",
      "Não sentir alongamento",
    ],
    benefits: [
      "Isolamento efetivo do peitoral",
      "Alongamento máximo",
      "Desenvolvimento da largura do peito",
      "Baixo estresse articular",
    ],
    scientificEvidence:
      "Exercício de isolamento que maximiza o alongamento do peitoral, crucial para desenvolvimento muscular.",
  },
  {
    id: "push-up-incline",
    name: "Flexão Inclinada",
    primaryMuscles: ["peito"],
    secondaryMuscles: ["ombros", "bracos"],
    difficulty: "iniciante",
    equipment: [],
    instructions: [
      "Posicione as mãos em uma superfície elevada (banco, parede)",
      "Mantenha corpo alinhado",
      "Desça o corpo até quase tocar a superfície",
      "Empurre de volta à posição inicial",
      "Quanto mais alta a superfície, mais fácil",
    ],
    tips: [
      "Ideal para iniciantes",
      "Progressão para flexão normal",
      "Mantenha forma correta",
      "Aumente dificuldade diminuindo altura",
    ],
    commonMistakes: [
      "Superfície muito alta (muito fácil)",
      "Não usar amplitude completa",
      "Forma incorreta",
    ],
    benefits: [
      "Progressão para flexão normal",
      "Desenvolvimento de força",
      "Acessível para iniciantes",
    ],
  },
  {
    id: "push-up-decline",
    name: "Flexão Declinada",
    primaryMuscles: ["peito"],
    secondaryMuscles: ["ombros", "bracos", "core"],
    difficulty: "intermediario",
    equipment: [],
    instructions: [
      "Posicione os pés em uma superfície elevada",
      "Mãos no chão na largura dos ombros",
      "Mantenha corpo alinhado",
      "Desça até quase tocar o chão",
      "Empurre de volta",
    ],
    tips: [
      "Trabalha mais a porção superior do peito",
      "Mais difícil que flexão normal",
      "Mantenha core forte",
      "Controle o movimento",
    ],
    commonMistakes: [
      "Elevação muito alta (perigoso)",
      "Forma incorreta",
      "Não controlar descida",
    ],
    benefits: [
      "Maior dificuldade",
      "Trabalha porção superior do peito",
      "Desenvolvimento de força",
    ],
  },
  {
    id: "pec-deck",
    name: "Voador (Pec Deck)",
    primaryMuscles: ["peito"],
    secondaryMuscles: ["ombros"],
    difficulty: "iniciante",
    equipment: ["Máquina"],
    instructions: [
      "Sente-se na máquina com costas apoiadas",
      "Ajuste altura dos braços",
      "Empurre os braços juntos até se tocarem",
      "Retorne controladamente sentindo alongamento",
      "Mantenha costas apoiadas",
    ],
    tips: [
      "Máquina segura para iniciantes",
      "Foque no alongamento e contração",
      "Não use peso excessivo",
      "Controle a fase excêntrica",
    ],
    commonMistakes: [
      "Peso excessivo",
      "Não usar amplitude completa",
      "Tirar costas do apoio",
      "Movimento muito rápido",
    ],
    benefits: [
      "Seguro para iniciantes",
      "Isolamento do peitoral",
      "Menor risco de lesão",
      "Boa para reabilitação",
    ],
  },
  {
    id: "cable-crossover",
    name: "Crossover no Cabo",
    primaryMuscles: ["peito"],
    secondaryMuscles: ["ombros"],
    difficulty: "intermediario",
    equipment: ["Cabos", "Polias"],
    instructions: [
      "Ajuste polias acima da altura dos ombros",
      "Fique no centro segurando os cabos",
      "Dê um passo à frente",
      "Traga os braços juntos cruzando à frente",
      "Retorne controladamente",
    ],
    tips: [
      "Pé à frente aumenta estabilidade",
      "Foque no peitoral, não nos ombros",
      "Controle o alongamento",
      "Não balance o corpo",
    ],
    commonMistakes: [
      "Balancear o corpo",
      "Usar ombros demais",
      "Não sentir alongamento",
      "Peso excessivo",
    ],
    benefits: [
      "Alongamento e contração máximos",
      "Desenvolvimento da largura do peito",
      "Tensão constante (cabos)",
      "Versatilidade de ângulos",
    ],
    scientificEvidence:
      "Crossover proporciona tensão constante e alongamento máximo do peitoral, ideal para hipertrofia.",
  },
  // ============================================
  // EXERCÍCIOS ADICIONAIS - COSTAS
  // ============================================
  {
    id: "bent-over-row",
    name: "Remada Curvada",
    primaryMuscles: ["costas"],
    secondaryMuscles: ["bracos", "ombros"],
    difficulty: "intermediario",
    equipment: ["Barra", "Anilhas"],
    instructions: [
      "Segure a barra com pegada pronada",
      "Flexione quadris mantendo costas retas",
      "Puxe a barra até o abdômen inferior",
      "Retraia as escápulas na contração",
      "Desça controladamente",
    ],
    tips: [
      "Mantenha costas sempre retas",
      "Puxe com as costas, não com os braços",
      "Retraia escápulas no topo",
      "Controle a descida",
    ],
    commonMistakes: [
      "Arredondar as costas",
      "Puxar com os braços",
      "Não retrair escápulas",
      "Peso excessivo",
    ],
    benefits: [
      "Desenvolvimento completo das costas",
      "Fortalecimento da cadeia posterior",
      "Melhora de postura",
      "Exercício composto",
    ],
    scientificEvidence:
      "Remada curvada é um dos exercícios mais efetivos para desenvolvimento do grande dorsal e romboides.",
  },
  {
    id: "seated-row",
    name: "Remada Sentada",
    primaryMuscles: ["costas"],
    secondaryMuscles: ["bracos", "ombros"],
    difficulty: "iniciante",
    equipment: ["Máquina", "Cabo"],
    instructions: [
      "Sente-se com pés apoiados",
      "Segure o cabo com pegada neutra",
      "Puxe até o abdômen",
      "Retraia escápulas",
      "Retorne controladamente",
    ],
    tips: [
      "Máquina segura para iniciantes",
      "Foque em retrair escápulas",
      "Não balance o corpo",
      "Controle a fase excêntrica",
    ],
    commonMistakes: [
      "Balancear o corpo",
      "Puxar com os braços",
      "Não retrair escápulas",
      "Puxar muito para trás",
    ],
    benefits: [
      "Seguro para iniciantes",
      "Isolamento das costas",
      "Menor risco de lesão",
      "Boa para reabilitação",
    ],
  },
  {
    id: "lat-pulldown",
    name: "Puxada Frontal",
    primaryMuscles: ["costas"],
    secondaryMuscles: ["bracos", "ombros"],
    difficulty: "iniciante",
    equipment: ["Máquina", "Cabo"],
    instructions: [
      "Sente-se na máquina com joelhos presos",
      "Segure a barra com pegada pronada",
      "Puxe a barra até o peito superior",
      "Retraia escápulas",
      "Retorne controladamente",
    ],
    tips: [
      "Ideal para quem não consegue fazer barra fixa",
      "Foque em puxar com as costas",
      "Não balance o corpo",
      "Controle a descida",
    ],
    commonMistakes: [
      "Puxar com os braços",
      "Balancear o corpo",
      "Não retrair escápulas",
      "Barra muito alta",
    ],
    benefits: [
      "Alternativa à barra fixa",
      "Desenvolvimento do grande dorsal",
      "Seguro para iniciantes",
      "Progressão para barra fixa",
    ],
    scientificEvidence:
      "Puxada frontal é uma excelente alternativa à barra fixa, com ativação similar do grande dorsal.",
  },
  {
    id: "t-bar-row",
    name: "Remada T",
    primaryMuscles: ["costas"],
    secondaryMuscles: ["bracos", "ombros"],
    difficulty: "intermediario",
    equipment: ["Barra T", "Anilhas"],
    instructions: [
      "Monte a barra T com peso",
      "Fique sobre a barra com pés apoiados",
      "Puxe a barra até o peito",
      "Retraia escápulas",
      "Desça controladamente",
    ],
    tips: [
      "Permite maior carga",
      "Movimento mais natural",
      "Foque nas costas",
      "Mantenha core ativo",
    ],
    commonMistakes: [
      "Arredondar costas",
      "Puxar com braços",
      "Não retrair escápulas",
      "Peso excessivo",
    ],
    benefits: [
      "Permite maior carga",
      "Desenvolvimento de força",
      "Movimento natural",
      "Exercício composto",
    ],
  },
  {
    id: "one-arm-row",
    name: "Remada Unilateral",
    primaryMuscles: ["costas"],
    secondaryMuscles: ["bracos", "ombros"],
    difficulty: "intermediario",
    equipment: ["Halter", "Banco"],
    instructions: [
      "Apoie joelho e mão no banco",
      "Segure halter com braço livre",
      "Puxe o halter até o quadril",
      "Retraia escápula",
      "Desça controladamente",
    ],
    tips: [
      "Corrige assimetrias",
      "Maior amplitude de movimento",
      "Foque em retrair escápula",
      "Mantenha costas retas",
    ],
    commonMistakes: [
      "Arredondar costas",
      "Rotacionar tronco",
      "Não retrair escápula",
      "Puxar com braço",
    ],
    benefits: [
      "Correção de assimetrias",
      "Maior amplitude",
      "Desenvolvimento unilateral",
      "Estabilização do core",
    ],
  },
  {
    id: "pullover",
    name: "Pullover",
    primaryMuscles: ["costas"],
    secondaryMuscles: ["peito", "ombros"],
    difficulty: "intermediario",
    equipment: ["Halter", "Banco"],
    instructions: [
      "Deite-se no banco segurando halter",
      "Braços estendidos acima do peito",
      "Desça o halter atrás da cabeça",
      "Sinta alongamento nas costas",
      "Retorne à posição inicial",
    ],
    tips: [
      "Foque no alongamento",
      "Mantenha leve flexão nos cotovelos",
      "Controle o movimento",
      "Sinta as costas trabalhando",
    ],
    commonMistakes: [
      "Estender demais cotovelos",
      "Não sentir alongamento",
      "Peso excessivo",
      "Movimento muito rápido",
    ],
    benefits: [
      "Alongamento máximo das costas",
      "Desenvolvimento de serrátil",
      "Expansão da caixa torácica",
      "Exercício único",
    ],
  },
  // ============================================
  // EXERCÍCIOS ADICIONAIS - PERNAS
  // ============================================
  {
    id: "leg-press",
    name: "Leg Press",
    primaryMuscles: ["pernas", "gluteos"],
    secondaryMuscles: ["core"],
    difficulty: "iniciante",
    equipment: ["Máquina"],
    instructions: [
      "Sente-se na máquina com pés na plataforma",
      "Pés na largura dos ombros",
      "Desça a plataforma flexionando joelhos",
      "Desça até 90 graus",
      "Empurre de volta",
    ],
    tips: [
      "Máquina segura para iniciantes",
      "Pés na largura dos ombros",
      "Não trave os joelhos",
      "Controle a descida",
    ],
    commonMistakes: [
      "Amplitude incompleta",
      "Joelhos colapsando",
      "Travar joelhos",
      "Peso excessivo",
    ],
    benefits: [
      "Seguro para iniciantes",
      "Permite maior carga",
      "Menor estresse na coluna",
      "Boa para reabilitação",
    ],
  },
  {
    id: "leg-curl-seated",
    name: "Cadeira Flexora",
    primaryMuscles: ["pernas"],
    secondaryMuscles: [],
    difficulty: "iniciante",
    equipment: ["Máquina"],
    instructions: [
      "Sente-se na máquina com pernas presas",
      "Flexione joelhos trazendo calcanhares ao glúteos",
      "Contraia isquiotibiais",
      "Retorne controladamente",
      "Mantenha costas apoiadas",
    ],
    tips: [
      "Isolamento dos isquiotibiais",
      "Controle a fase excêntrica",
      "Não use impulso",
      "Sinta os músculos trabalhando",
    ],
    commonMistakes: [
      "Usar impulso",
      "Não controlar descida",
      "Amplitude incompleta",
      "Peso excessivo",
    ],
    benefits: [
      "Isolamento de isquiotibiais",
      "Equilíbrio muscular",
      "Prevenção de lesões",
      "Seguro para iniciantes",
    ],
  },
  {
    id: "leg-extension",
    name: "Cadeira Extensora",
    primaryMuscles: ["pernas"],
    secondaryMuscles: [],
    difficulty: "iniciante",
    equipment: ["Máquina"],
    instructions: [
      "Sente-se na máquina com pernas presas",
      "Estenda joelhos completamente",
      "Contraia quadríceps",
      "Retorne controladamente",
      "Mantenha costas apoiadas",
    ],
    tips: [
      "Isolamento do quadríceps",
      "Controle a fase excêntrica",
      "Não trave joelhos",
      "Sinta o quadríceps",
    ],
    commonMistakes: [
      "Travar joelhos",
      "Não controlar descida",
      "Peso excessivo",
      "Amplitude incompleta",
    ],
    benefits: [
      "Isolamento do quadríceps",
      "Desenvolvimento de força",
      "Boa para reabilitação",
      "Seguro para iniciantes",
    ],
  },
  {
    id: "bulgarian-split-squat",
    name: "Agachamento Búlgaro",
    primaryMuscles: ["pernas", "gluteos"],
    secondaryMuscles: ["core"],
    difficulty: "intermediario",
    equipment: ["Halteres"],
    instructions: [
      "Pé traseiro apoiado em banco",
      "Pé dianteiro à frente",
      "Desça flexionando joelho dianteiro",
      "Desça até coxa paralela ao chão",
      "Empurre de volta",
    ],
    tips: [
      "Trabalha pernas unilateralmente",
      "Corrige assimetrias",
      "Mantenha tronco ereto",
      "Foque no pé da frente",
    ],
    commonMistakes: [
      "Joelho passando dos dedos",
      "Tronco inclinando",
      "Não usar amplitude completa",
      "Peso excessivo",
    ],
    benefits: [
      "Trabalho unilateral",
      "Correção de assimetrias",
      "Desenvolvimento de força",
      "Estabilização",
    ],
  },
  {
    id: "lunge",
    name: "Avanço (Lunge)",
    primaryMuscles: ["pernas", "gluteos"],
    secondaryMuscles: ["core"],
    difficulty: "intermediario",
    equipment: ["Halteres"],
    instructions: [
      "Dê um passo à frente",
      "Desça flexionando ambos joelhos",
      "Joelho traseiro quase toca o chão",
      "Joelho dianteiro a 90 graus",
      "Empurre de volta",
    ],
    tips: [
      "Trabalho funcional",
      "Mantenha tronco ereto",
      "Passo longo para mais glúteos",
      "Passo curto para mais quadríceps",
    ],
    commonMistakes: [
      "Joelho passando dos dedos",
      "Tronco inclinando",
      "Não usar amplitude completa",
      "Joelhos colapsando",
    ],
    benefits: [
      "Exercício funcional",
      "Desenvolvimento de força",
      "Melhora de equilíbrio",
      "Trabalho unilateral",
    ],
  },
  {
    id: "calf-raise",
    name: "Elevação de Panturrilha",
    primaryMuscles: ["pernas"],
    secondaryMuscles: [],
    difficulty: "iniciante",
    equipment: ["Máquina"],
    instructions: [
      "Posicione ombros sob a máquina",
      "Pés na plataforma",
      "Elevação máxima na ponta dos pés",
      "Contraia panturrilhas",
      "Desça controladamente",
    ],
    tips: [
      "Amplitude completa",
      "Controle a fase excêntrica",
      "Pode fazer em pé ou sentado",
      "Sinta as panturrilhas",
    ],
    commonMistakes: [
      "Amplitude incompleta",
      "Não controlar descida",
      "Peso excessivo",
      "Balancear",
    ],
    benefits: [
      "Desenvolvimento de panturrilhas",
      "Melhora de estética",
      "Força funcional",
      "Equilíbrio",
    ],
  },
  // ============================================
  // EXERCÍCIOS ADICIONAIS - OMBROS
  // ============================================
  {
    id: "shoulder-press",
    name: "Desenvolvimento",
    primaryMuscles: ["ombros"],
    secondaryMuscles: ["bracos", "core"],
    difficulty: "intermediario",
    equipment: ["Halteres", "Barra"],
    instructions: [
      "Segure halteres na altura dos ombros",
      "Palmas para frente",
      "Empurre para cima até extensão completa",
      "Não trave os cotovelos",
      "Desça controladamente",
    ],
    tips: [
      "Pode fazer sentado ou em pé",
      "Sentado é mais seguro",
      "Mantenha core ativo",
      "Controle o movimento",
    ],
    commonMistakes: [
      "Arquear excessivamente as costas",
      "Não usar amplitude completa",
      "Travar cotovelos",
      "Peso excessivo",
    ],
    benefits: [
      "Desenvolvimento completo dos ombros",
      "Força funcional",
      "Exercício composto",
      "Transferência para movimentos diários",
    ],
  },
  {
    id: "lateral-raise",
    name: "Elevação Lateral",
    primaryMuscles: ["ombros"],
    secondaryMuscles: [],
    difficulty: "iniciante",
    equipment: ["Halteres"],
    instructions: [
      "Segure halteres ao lado do corpo",
      "Braços ligeiramente flexionados",
      "Eleve até altura dos ombros",
      "Contraia deltoides",
      "Desça controladamente",
    ],
    tips: [
      "Isolamento do deltoide médio",
      "Não balance o corpo",
      "Controle o movimento",
      "Sinta os ombros trabalhando",
    ],
    commonMistakes: [
      "Balancear o corpo",
      "Peso excessivo",
      "Elevar muito alto",
      "Usar impulso",
    ],
    benefits: [
      "Desenvolvimento da largura dos ombros",
      "Isolamento efetivo",
      "Estética",
      "Força funcional",
    ],
  },
  {
    id: "front-raise",
    name: "Elevação Frontal",
    primaryMuscles: ["ombros"],
    secondaryMuscles: [],
    difficulty: "iniciante",
    equipment: ["Halteres"],
    instructions: [
      "Segure halteres à frente do corpo",
      "Eleve até altura dos ombros",
      "Contraia deltoide anterior",
      "Desça controladamente",
      "Mantenha braços estendidos",
    ],
    tips: [
      "Isolamento do deltoide anterior",
      "Controle o movimento",
      "Não balance",
      "Sinta os ombros",
    ],
    commonMistakes: [
      "Balancear",
      "Peso excessivo",
      "Elevar muito alto",
      "Usar impulso",
    ],
    benefits: [
      "Desenvolvimento do deltoide anterior",
      "Isolamento",
      "Estética",
    ],
  },
  {
    id: "rear-delt-fly",
    name: "Voador Invertido",
    primaryMuscles: ["ombros"],
    secondaryMuscles: ["costas"],
    difficulty: "iniciante",
    equipment: ["Halteres"],
    instructions: [
      "Flexione quadris mantendo costas retas",
      "Braços ligeiramente flexionados",
      "Abra os braços até altura dos ombros",
      "Contraia deltoides posteriores",
      "Retorne controladamente",
    ],
    tips: [
      "Crucial para saúde dos ombros",
      "Foque nos deltoides posteriores",
      "Mantenha costas retas",
      "Controle o movimento",
    ],
    commonMistakes: [
      "Arredondar costas",
      "Peso excessivo",
      "Não sentir deltoides posteriores",
      "Movimento muito rápido",
    ],
    benefits: [
      "Desenvolvimento de deltoides posteriores",
      "Saúde dos ombros",
      "Correção de postura",
      "Prevenção de lesões",
    ],
    scientificEvidence:
      "Deltoides posteriores são frequentemente negligenciados, causando desequilíbrios e problemas nos ombros.",
  },
  {
    id: "arnold-press",
    name: "Desenvolvimento Arnold",
    primaryMuscles: ["ombros"],
    secondaryMuscles: ["bracos"],
    difficulty: "intermediario",
    equipment: ["Halteres"],
    instructions: [
      "Comece com halteres na frente, palmas para você",
      "Rotacione enquanto empurra para cima",
      "Termine com palmas para frente",
      "Inverta o movimento na descida",
      "Controle todo o movimento",
    ],
    tips: [
      "Trabalha todas as porções do deltoide",
      "Movimento complexo",
      "Controle total necessário",
      "Não use peso excessivo",
    ],
    commonMistakes: [
      "Peso excessivo",
      "Movimento muito rápido",
      "Não controlar rotação",
      "Forma incorreta",
    ],
    benefits: [
      "Desenvolvimento completo dos ombros",
      "Movimento único",
      "Ativação de todas as porções",
    ],
  },
  // ============================================
  // EXERCÍCIOS ADICIONAIS - BRAÇOS
  // ============================================
  {
    id: "bicep-curl",
    name: "Rosca Direta",
    primaryMuscles: ["bracos"],
    secondaryMuscles: [],
    difficulty: "iniciante",
    equipment: ["Halteres"],
    instructions: [
      "Segure halteres ao lado do corpo",
      "Flexione cotovelos trazendo halteres aos ombros",
      "Contraia bíceps",
      "Desça controladamente",
      "Mantenha cotovelos fixos",
    ],
    tips: [
      "Isolamento de bíceps",
      "Mantenha cotovelos fixos",
      "Controle a fase excêntrica",
      "Não balance o corpo",
    ],
    commonMistakes: [
      "Balancear o corpo",
      "Mover cotovelos",
      "Peso excessivo",
      "Não controlar descida",
    ],
    benefits: ["Desenvolvimento de bíceps", "Isolamento efetivo", "Estética"],
  },
  {
    id: "hammer-curl",
    name: "Rosca Martelo",
    primaryMuscles: ["bracos"],
    secondaryMuscles: [],
    difficulty: "iniciante",
    equipment: ["Halteres"],
    instructions: [
      "Segure halteres com pegada neutra",
      "Flexione cotovelos",
      "Contraia bíceps e antebraços",
      "Desça controladamente",
      "Mantenha pegada neutra",
    ],
    tips: [
      "Trabalha bíceps e antebraços",
      "Pegada neutra",
      "Controle o movimento",
      "Sinta ambos trabalhando",
    ],
    commonMistakes: [
      "Balancear",
      "Mover cotovelos",
      "Peso excessivo",
      "Não controlar",
    ],
    benefits: [
      "Desenvolvimento de bíceps e antebraços",
      "Espessura do braço",
      "Força de pegada",
    ],
  },
  {
    id: "tricep-dip",
    name: "Mergulho (Tríceps)",
    primaryMuscles: ["bracos"],
    secondaryMuscles: ["ombros", "peito"],
    difficulty: "intermediario",
    equipment: ["Barras Paralelas"],
    instructions: [
      "Segure barras paralelas",
      "Mantenha corpo ereto",
      "Desça flexionando cotovelos",
      "Desça até 90 graus",
      "Empurre de volta",
    ],
    tips: [
      "Corpo ereto trabalha mais tríceps",
      "Não descer demais",
      "Controle o movimento",
      "Mantenha core ativo",
    ],
    commonMistakes: [
      "Descer demais",
      "Balancear",
      "Não controlar",
      "Forma incorreta",
    ],
    benefits: [
      "Desenvolvimento de tríceps",
      "Exercício composto",
      "Força funcional",
    ],
  },
  {
    id: "tricep-kickback",
    name: "Tríceps Coice",
    primaryMuscles: ["bracos"],
    secondaryMuscles: [],
    difficulty: "iniciante",
    equipment: ["Halter"],
    instructions: [
      "Apoie joelho e mão no banco",
      "Segure halter com braço livre",
      "Cotovelo a 90 graus",
      "Estenda braço para trás",
      "Contraia tríceps",
    ],
    tips: [
      "Isolamento de tríceps",
      "Mantenha cotovelo fixo",
      "Controle o movimento",
      "Sinta o tríceps",
    ],
    commonMistakes: [
      "Mover cotovelo",
      "Peso excessivo",
      "Não controlar",
      "Não sentir tríceps",
    ],
    benefits: ["Isolamento de tríceps", "Desenvolvimento", "Estética"],
  },
  {
    id: "close-grip-bench",
    name: "Supino Fechado",
    primaryMuscles: ["bracos"],
    secondaryMuscles: ["peito", "ombros"],
    difficulty: "intermediario",
    equipment: ["Barra", "Banco", "Anilhas"],
    instructions: [
      "Deite-se no banco",
      "Pegada fechada (mãos na largura dos ombros)",
      "Desça barra até o peito",
      "Empurre focando em tríceps",
      "Mantenha cotovelos junto ao corpo",
    ],
    tips: [
      "Excelente para tríceps",
      "Cotovelos junto ao corpo",
      "Foque em tríceps",
      "Controle o movimento",
    ],
    commonMistakes: [
      "Abrir cotovelos",
      "Pegada muito fechada",
      "Não focar em tríceps",
      "Peso excessivo",
    ],
    benefits: ["Desenvolvimento de tríceps", "Exercício composto", "Força"],
  },
  {
    id: "preacher-curl",
    name: "Rosca Scott",
    primaryMuscles: ["bracos"],
    secondaryMuscles: [],
    difficulty: "iniciante",
    equipment: ["Máquina", "Barra"],
    instructions: [
      "Apoie braços no banco Scott",
      "Segure barra",
      "Flexione cotovelos",
      "Contraia bíceps",
      "Desça controladamente",
    ],
    tips: [
      "Isolamento máximo de bíceps",
      "Controle a fase excêntrica",
      "Sinta os bíceps",
      "Não use impulso",
    ],
    commonMistakes: [
      "Usar impulso",
      "Peso excessivo",
      "Não controlar",
      "Amplitude incompleta",
    ],
    benefits: ["Isolamento máximo", "Desenvolvimento de bíceps", "Estética"],
  },
  // ============================================
  // EXERCÍCIOS ADICIONAIS - CORE
  // ============================================
  {
    id: "plank",
    name: "Prancha",
    primaryMuscles: ["core"],
    secondaryMuscles: ["ombros"],
    difficulty: "iniciante",
    equipment: [],
    instructions: [
      "Posicione-se em prancha",
      "Apoie antebraços e pés",
      "Mantenha corpo alinhado",
      "Contraia core",
      "Mantenha posição",
    ],
    tips: [
      "Exercício isométrico",
      "Mantenha corpo alinhado",
      "Respire normalmente",
      "Contraia core",
    ],
    commonMistakes: [
      "Arquear ou afundar costas",
      "Cabeça para baixo",
      "Não contrair core",
      "Segurar respiração",
    ],
    benefits: [
      "Fortalecimento de core",
      "Estabilidade",
      "Sem equipamento",
      "Prevenção de lesões",
    ],
    scientificEvidence:
      "Prancha é um dos exercícios mais efetivos para desenvolvimento de força isométrica do core.",
  },
  {
    id: "crunch",
    name: "Abdominal",
    primaryMuscles: ["core"],
    secondaryMuscles: [],
    difficulty: "iniciante",
    equipment: [],
    instructions: [
      "Deite-se com joelhos flexionados",
      "Mãos atrás da cabeça",
      "Contraia abdômen",
      "Eleve tronco parcialmente",
      "Retorne controladamente",
    ],
    tips: [
      "Foque em contrair abdômen",
      "Não puxar pescoço",
      "Movimento curto",
      "Controle o movimento",
    ],
    commonMistakes: [
      "Puxar pescoço",
      "Movimento muito longo",
      "Usar impulso",
      "Não contrair abdômen",
    ],
    benefits: ["Desenvolvimento de abdômen", "Sem equipamento", "Acessível"],
  },
  {
    id: "mountain-climber",
    name: "Escalador",
    primaryMuscles: ["core"],
    secondaryMuscles: ["pernas", "ombros"],
    difficulty: "intermediario",
    equipment: [],
    instructions: [
      "Posicione-se em prancha",
      "Alternne pernas rapidamente",
      "Traga joelho ao peito",
      "Mantenha core contraído",
      "Ritmo constante",
    ],
    tips: [
      "Exercício dinâmico",
      "Mantenha core ativo",
      "Ritmo constante",
      "Controle o movimento",
    ],
    commonMistakes: [
      "Arquear costas",
      "Ritmo irregular",
      "Não contrair core",
      "Movimento muito rápido",
    ],
    benefits: ["Cardio e core", "Queima calórica", "Força funcional"],
  },
  {
    id: "dead-bug",
    name: "Inseto Morto",
    primaryMuscles: ["core"],
    secondaryMuscles: [],
    difficulty: "iniciante",
    equipment: [],
    instructions: [
      "Deite-se de costas",
      "Braços e pernas no ar",
      "Estenda braço e perna opostos",
      "Retorne à posição inicial",
      "Alternne lados",
    ],
    tips: [
      "Excelente para iniciantes",
      "Mantenha costas no chão",
      "Controle o movimento",
      "Foque em estabilidade",
    ],
    commonMistakes: [
      "Arquear costas",
      "Movimento muito rápido",
      "Não controlar",
      "Perder estabilidade",
    ],
    benefits: [
      "Estabilidade do core",
      "Seguro para iniciantes",
      "Prevenção de lesões",
    ],
  },
  {
    id: "hanging-leg-raise",
    name: "Elevação de Pernas na Barra",
    primaryMuscles: ["core"],
    secondaryMuscles: ["pernas"],
    difficulty: "avancado",
    equipment: ["Barra Fixa"],
    instructions: [
      "Segure a barra",
      "Mantenha corpo estável",
      "Eleve pernas até altura dos quadris",
      "Contraia abdômen",
      "Desça controladamente",
    ],
    tips: [
      "Exercício avançado",
      "Mantenha corpo estável",
      "Foque em abdômen",
      "Controle o movimento",
    ],
    commonMistakes: [
      "Balancear",
      "Usar impulso",
      "Não contrair abdômen",
      "Forma incorreta",
    ],
    benefits: [
      "Desenvolvimento avançado de core",
      "Força funcional",
      "Estética",
    ],
  },
  // ============================================
  // EXERCÍCIOS ADICIONAIS - CARDIO E FUNCIONAL
  // ============================================
  {
    id: "burpee",
    name: "Burpee",
    primaryMuscles: ["cardio", "funcional"],
    secondaryMuscles: ["pernas", "core", "ombros"],
    difficulty: "avancado",
    equipment: [],
    instructions: [
      "Comece em pé",
      "Desça em agachamento",
      "Salte para prancha",
      "Faça uma flexão",
      "Volte e salte",
    ],
    tips: [
      "Exercício completo",
      "Alta intensidade",
      "Controle a respiração",
      "Mantenha forma correta",
    ],
    commonMistakes: [
      "Forma incorreta",
      "Não fazer flexão completa",
      "Ritmo irregular",
      "Não controlar movimento",
    ],
    benefits: [
      "Alto gasto calórico",
      "Exercício completo",
      "Melhora de condicionamento",
      "Força funcional",
    ],
  },
  {
    id: "jumping-jack",
    name: "Polichinelo",
    primaryMuscles: ["cardio"],
    secondaryMuscles: ["pernas", "ombros"],
    difficulty: "iniciante",
    equipment: [],
    instructions: [
      "Fique em pé",
      "Salte abrindo pernas e braços",
      "Volte à posição inicial",
      "Mantenha ritmo constante",
    ],
    tips: [
      "Aquecimento excelente",
      "Ritmo constante",
      "Controle aterrissagem",
      "Mantenha core ativo",
    ],
    commonMistakes: [
      "Aterrissagem dura",
      "Ritmo irregular",
      "Não controlar movimento",
    ],
    benefits: ["Aquecimento", "Cardio leve", "Coordenação", "Acessível"],
  },
  {
    id: "high-knee",
    name: "Joelho Alto",
    primaryMuscles: ["cardio"],
    secondaryMuscles: ["pernas", "core"],
    difficulty: "iniciante",
    equipment: [],
    instructions: [
      "Fique em pé",
      "Eleve joelhos alternadamente",
      "Ritmo rápido",
      "Mantenha core ativo",
    ],
    tips: [
      "Aquecimento",
      "Ritmo constante",
      "Mantenha postura",
      "Controle movimento",
    ],
    commonMistakes: [
      "Ritmo irregular",
      "Postura incorreta",
      "Não elevar joelhos",
    ],
    benefits: ["Aquecimento", "Cardio", "Coordenação"],
  },
  {
    id: "box-jump",
    name: "Salto no Caixote",
    primaryMuscles: ["funcional"],
    secondaryMuscles: ["pernas", "gluteos", "core"],
    difficulty: "avancado",
    equipment: ["Caixote"],
    instructions: [
      "Fique frente ao caixote",
      "Salte sobre o caixote",
      "Aterrisse com ambos pés",
      "Desça controladamente",
    ],
    tips: [
      "Exercício avançado",
      "Comece com altura baixa",
      "Controle aterrissagem",
      "Mantenha core ativo",
    ],
    commonMistakes: [
      "Altura muito alta",
      "Aterrissagem dura",
      "Não controlar",
      "Forma incorreta",
    ],
    benefits: ["Potência", "Força funcional", "Coordenação", "Condicionamento"],
  },
  {
    id: "kettlebell-swing",
    name: "Balancinho com Kettlebell",
    primaryMuscles: ["funcional"],
    secondaryMuscles: ["gluteos", "pernas", "core", "ombros"],
    difficulty: "intermediario",
    equipment: ["Kettlebell"],
    instructions: [
      "Segure kettlebell com ambas mãos",
      "Flexione quadris",
      "Balance kettlebell até altura dos ombros",
      "Use impulso dos quadris",
      "Controle descida",
    ],
    tips: [
      "Exercício funcional completo",
      "Foque em quadris, não braços",
      "Controle o movimento",
      "Mantenha core ativo",
    ],
    commonMistakes: [
      "Usar braços demais",
      "Não usar quadris",
      "Peso excessivo",
      "Forma incorreta",
    ],
    benefits: [
      "Exercício funcional completo",
      "Potência",
      "Condicionamento",
      "Força posterior",
    ],
    scientificEvidence:
      "Kettlebell swing é um dos exercícios mais efetivos para desenvolvimento de potência e condicionamento.",
  },
  {
    id: "battle-rope",
    name: "Corda de Batalha",
    primaryMuscles: ["cardio", "funcional"],
    secondaryMuscles: ["ombros", "core", "bracos"],
    difficulty: "intermediario",
    equipment: ["Corda de Batalha"],
    instructions: [
      "Segure corda com ambas mãos",
      "Crie ondas alternadas",
      "Mantenha ritmo constante",
      "Use corpo todo",
    ],
    tips: [
      "Alta intensidade",
      "Ritmo constante",
      "Use corpo todo",
      "Controle respiração",
    ],
    commonMistakes: [
      "Usar apenas braços",
      "Ritmo irregular",
      "Não usar core",
      "Fadiga rápida",
    ],
    benefits: [
      "Alto gasto calórico",
      "Condicionamento",
      "Força funcional",
      "Exercício completo",
    ],
  },
  {
    id: "farmer-walk",
    name: "Caminhada do Fazendeiro",
    primaryMuscles: ["funcional"],
    secondaryMuscles: ["core", "ombros", "bracos"],
    difficulty: "intermediario",
    equipment: ["Halteres", "Kettlebells"],
    instructions: [
      "Segure peso em cada mão",
      "Mantenha postura ereta",
      "Caminhe distância determinada",
      "Mantenha core ativo",
      "Controle respiração",
    ],
    tips: [
      "Exercício funcional",
      "Mantenha postura",
      "Core sempre ativo",
      "Controle o movimento",
    ],
    commonMistakes: [
      "Postura incorreta",
      "Não contrair core",
      "Peso desequilibrado",
      "Forma incorreta",
    ],
    benefits: [
      "Força funcional",
      "Estabilidade",
      "Força de pegada",
      "Condicionamento",
    ],
  },
  {
    id: "turkish-get-up",
    name: "Levantamento Turco",
    primaryMuscles: ["funcional"],
    secondaryMuscles: ["core", "ombros", "pernas"],
    difficulty: "avancado",
    equipment: ["Kettlebell"],
    instructions: [
      "Deite-se segurando kettlebell",
      "Eleve kettlebell com um braço",
      "Levante-se em etapas",
      "Mantenha kettlebell estável",
      "Inverta movimento",
    ],
    tips: [
      "Exercício avançado",
      "Movimento complexo",
      "Controle total necessário",
      "Comece sem peso",
    ],
    commonMistakes: [
      "Peso excessivo",
      "Forma incorreta",
      "Não controlar movimento",
      "Kettlebell instável",
    ],
    benefits: [
      "Exercício funcional completo",
      "Estabilidade",
      "Coordenação",
      "Força",
    ],
    scientificEvidence:
      "Turkish get-up é considerado um dos exercícios mais completos para desenvolvimento de força funcional e estabilidade.",
  },
  {
    id: "prowler-push",
    name: "Empurrar Trenó",
    primaryMuscles: ["funcional"],
    secondaryMuscles: ["pernas", "gluteos", "core", "ombros"],
    difficulty: "avancado",
    equipment: ["Trenó"],
    instructions: [
      "Posicione-se atrás do trenó",
      "Empurre com corpo todo",
      "Mantenha postura baixa",
      "Use pernas e core",
      "Controle o movimento",
    ],
    tips: [
      "Exercício avançado",
      "Alta intensidade",
      "Use corpo todo",
      "Controle respiração",
    ],
    commonMistakes: [
      "Usar apenas braços",
      "Postura incorreta",
      "Não usar pernas",
      "Fadiga rápida",
    ],
    benefits: [
      "Alto gasto calórico",
      "Potência",
      "Condicionamento",
      "Força funcional",
    ],
  },
  {
    id: "sled-pull",
    name: "Puxar Trenó",
    primaryMuscles: ["funcional"],
    secondaryMuscles: ["costas", "pernas", "gluteos", "core"],
    difficulty: "avancado",
    equipment: ["Trenó"],
    instructions: [
      "Segure corda do trenó",
      "Puxe caminhando para trás",
      "Use corpo todo",
      "Mantenha postura",
      "Controle o movimento",
    ],
    tips: [
      "Exercício avançado",
      "Use corpo todo",
      "Mantenha postura",
      "Controle respiração",
    ],
    commonMistakes: [
      "Postura incorreta",
      "Não usar corpo todo",
      "Fadiga rápida",
      "Forma incorreta",
    ],
    benefits: [
      "Alto gasto calórico",
      "Força posterior",
      "Condicionamento",
      "Força funcional",
    ],
  },
];
