FROM oven/bun:latest
WORKDIR /app

COPY package.json bun.lockb* package-lock.json* pnpm-lock.yaml* ./
COPY prisma/schema.prisma ./prisma/schema.prisma
RUN bun install

COPY . .

ENV NODE_ENV=development
ENV PORT=3000
ENV HOST=0.0.0.0

EXPOSE 3000
CMD ["bun", "--bun", "server/custom-server.ts"]
