import type { EducationalLesson, ExerciseInfo, MuscleInfo } from "../types";

export const muscleDatabase: MuscleInfo[] = [
	{
		id: "pectoralis-major",
		name: "Peitoral Maior",
		scientificName: "Pectoralis Major",
		group: "peito",
		description:
			"Músculo grande e em forma de leque que cobre a maior parte da parede torácica anterior.",
		functions: [
			"Adução do braço (trazer o braço em direção ao corpo)",
			"Flexão do ombro (elevar o braço para frente)",
			"Rotação interna do braço",
			"Auxilia na respiração forçada",
		],
		commonExercises: [
			"Supino reto",
			"Supino inclinado",
			"Crucifixo",
			"Flexão de braço",
			"Crossover",
		],
		anatomyFacts: [
			"Possui duas cabeças: clavicular (superior) e esternocostal (inferior)",
			"A cabeça clavicular é mais ativada em movimentos inclinados",
			"É um dos músculos mais treináveis e responsivos do corpo",
			"Recebe suprimento sanguíneo das artérias torácica e acromial",
		],
	},
	{
		id: "latissimus-dorsi",
		name: "Grande Dorsal",
		scientificName: "Latissimus Dorsi",
		group: "costas",
		description:
			"O músculo mais largo das costas, responsável pela aparência em V do tronco.",
		functions: [
			"Extensão do ombro (puxar o braço para trás)",
			"Adução do braço",
			"Rotação interna do ombro",
			"Auxilia na respiração forçada",
		],
		commonExercises: [
			"Barra fixa",
			"Pulldown",
			"Remada curvada",
			"Pullover",
			"Remada unilateral",
		],
		anatomyFacts: [
			"Origina-se na coluna vertebral inferior e pelve",
			"Insere-se no úmero (osso do braço)",
			"É o músculo mais largo do corpo humano",
			"Crucial para movimentos de escalada e natação",
		],
	},
	{
		id: "quadriceps",
		name: "Quadríceps",
		scientificName: "Quadriceps Femoris",
		group: "pernas",
		description:
			"Grupo muscular composto por quatro músculos na parte frontal da coxa.",
		functions: [
			"Extensão do joelho (esticar a perna)",
			"Flexão do quadril (reto femoral)",
			"Estabilização da patela",
			"Suporte para caminhar, correr e pular",
		],
		commonExercises: [
			"Agachamento",
			"Leg press",
			"Cadeira extensora",
			"Avanço",
			"Afundo",
		],
		anatomyFacts: [
			"Composto por: reto femoral, vasto lateral, vasto medial e vasto intermédio",
			"O reto femoral é o único que cruza duas articulações (quadril e joelho)",
			"Vasto medial é crucial para estabilidade do joelho",
			"Um dos grupos musculares mais fortes do corpo",
		],
	},
	{
		id: "deltoid",
		name: "Deltoide",
		scientificName: "Deltoideus",
		group: "ombros",
		description:
			"Músculo triangular que cobre a articulação do ombro, responsável pela aparência arredondada.",
		functions: [
			"Abdução do braço (elevar lateralmente)",
			"Flexão do ombro (deltoide anterior)",
			"Extensão do ombro (deltoide posterior)",
			"Rotação do braço",
		],
		commonExercises: [
			"Desenvolvimento militar",
			"Elevação lateral",
			"Elevação frontal",
			"Remada alta",
			"Crucifixo invertido",
		],
		anatomyFacts: [
			"Possui três cabeças: anterior, lateral e posterior",
			"Cada cabeça tem funções distintas",
			"Essencial para a mobilidade do ombro em todos os planos",
			"Altamente vascularizado, permitindo recuperação rápida",
		],
	},
	{
		id: "biceps-brachii",
		name: "Bíceps Braquial",
		scientificName: "Biceps Brachii",
		group: "bracos",
		description:
			"Músculo de duas cabeças localizado na parte frontal do braço.",
		functions: [
			"Flexão do cotovelo (dobrar o braço)",
			"Supinação do antebraço (virar a palma para cima)",
			"Flexão leve do ombro",
			"Estabilização do ombro",
		],
		commonExercises: [
			"Rosca direta",
			"Rosca martelo",
			"Rosca scott",
			"Rosca inclinada",
			"Rosca concentrada",
		],
		anatomyFacts: [
			"Possui cabeça longa e cabeça curta",
			"A cabeça longa é mais ativa na rosca inclinada",
			"Atravessa duas articulações: ombro e cotovelo",
			"Trabalha em conjunto com o braquial para flexão do cotovelo",
		],
	},
	{
		id: "rectus-abdominis",
		name: "Reto Abdominal",
		scientificName: "Rectus Abdominis",
		group: "core",
		description:
			"Músculo longo e plano que forma os 'gominhos' abdominais quando desenvolvido.",
		functions: [
			"Flexão do tronco (aproximar tórax da pelve)",
			"Estabilização da coluna vertebral",
			"Compressão dos órgãos abdominais",
			"Auxilia na respiração forçada e tosse",
		],
		commonExercises: [
			"Abdominal tradicional",
			"Crunch",
			"Elevação de pernas",
			"Prancha",
			"Abdominal na roldana",
		],
		anatomyFacts: [
			"Separado pela linha alba no centro",
			"Dividido por intersecções tendíneas que criam os 'gominhos'",
			"O número de gominhos visíveis é genético",
			"Trabalha 24/7 para estabilização postural",
		],
	},
	{
		id: "gluteus-maximus",
		name: "Glúteo Máximo",
		scientificName: "Gluteus Maximus",
		group: "gluteos",
		description:
			"O maior e mais superficial dos três músculos glúteos, formando as nádegas.",
		functions: [
			"Extensão do quadril (levar a perna para trás)",
			"Rotação lateral do quadril",
			"Estabilização da pelve",
			"Auxílio na posição ereta",
		],
		commonExercises: [
			"Agachamento",
			"Levantamento terra",
			"Hip thrust",
			"Stiff",
			"Passada",
		],
		anatomyFacts: [
			"É o maior músculo do corpo humano",
			"Crucial para locomoção bípede (andar ereto)",
			"Altamente responsivo a treino de força",
			"Essencial para corrida e saltos",
		],
	},
	{
		id: "triceps-brachii",
		name: "Tríceps Braquial",
		scientificName: "Triceps Brachii",
		group: "bracos",
		description:
			"Músculo de três cabeças na parte posterior do braço, responsável por 2/3 do volume do braço.",
		functions: [
			"Extensão do cotovelo (esticar o braço)",
			"Extensão do ombro (cabeça longa)",
			"Estabilização do ombro",
			"Adução do braço (cabeça longa)",
		],
		commonExercises: [
			"Tríceps testa",
			"Tríceps pulley",
			"Paralelas",
			"Tríceps francês",
			"Fundos",
		],
		anatomyFacts: [
			"Possui três cabeças: longa, lateral e medial",
			"Representa aproximadamente 60% do volume do braço",
			"A cabeça longa cruza duas articulações (ombro e cotovelo)",
			"Trabalha ativamente em movimentos de empurrar",
		],
	},
	{
		id: "trapezius",
		name: "Trapézio",
		scientificName: "Trapezius",
		group: "costas",
		description:
			"Músculo grande em formato de trapézio que cobre a parte superior das costas e pescoço.",
		functions: [
			"Elevação das escápulas (parte superior)",
			"Retração das escápulas (parte média)",
			"Depressão das escápulas (parte inferior)",
			"Rotação superior das escápulas",
		],
		commonExercises: [
			"Encolhimento",
			"Remada alta",
			"Remada curvada",
			"Puxada alta",
			"Face pull",
		],
		anatomyFacts: [
			"Dividido em três porções: superior, média e inferior",
			"A porção superior é a mais visível (formato de armadilha)",
			"Crucial para estabilização das escápulas",
			"Trabalha constantemente na postura ereta",
		],
	},
	{
		id: "rhomboids",
		name: "Romboide",
		scientificName: "Rhomboid Major & Minor",
		group: "costas",
		description:
			"Par de músculos localizados entre as escápulas, essenciais para a postura.",
		functions: [
			"Retração das escápulas (puxar para trás)",
			"Elevação das escápulas",
			"Rotação inferior das escápulas",
			"Estabilização das escápulas",
		],
		commonExercises: [
			"Remada curvada",
			"Remada no cabo",
			"Remada T",
			"Retração de escápulas",
			"Face pull",
		],
		anatomyFacts: [
			"Composto por romboide maior e romboide menor",
			"Localizado profundamente ao trapézio médio",
			"Crucial para corrigir ombros arredondados",
			"Fraqueza leva a má postura e dor",
		],
	},
	{
		id: "erector-spinae",
		name: "Eretor da Espinha",
		scientificName: "Erector Spinae",
		group: "costas",
		description:
			"Grupo de músculos que correm ao longo da coluna vertebral, essenciais para manter a postura.",
		functions: [
			"Extensão da coluna vertebral",
			"Rotação lateral da coluna",
			"Estabilização da coluna",
			"Manutenção da postura ereta",
		],
		commonExercises: [
			"Hiperextensão",
			"Boa manhã",
			"Levantamento terra",
			"Prancha",
			"Superman",
		],
		anatomyFacts: [
			"Composto por três colunas: ilicostal, longuíssimo e espinhal",
			"Estende-se da pelve até o crânio",
			"Crucial para prevenir lesões na coluna",
			"Ativo durante todo o dia na postura",
		],
	},
	{
		id: "oblique-abdominis",
		name: "Abdominal Oblíquo",
		scientificName: "Obliquus Externus & Internus Abdominis",
		group: "core",
		description:
			"Músculos localizados nas laterais do tronco, formando a 'cintura'.",
		functions: [
			"Rotação do tronco",
			"Flexão lateral do tronco",
			"Compressão abdominal",
			"Estabilização da coluna",
		],
		commonExercises: [
			"Prancha lateral",
			"Russian twist",
			"Abdominal oblíquo",
			"Side plank",
			"Cable woodchop",
		],
		anatomyFacts: [
			"Dividido em oblíquo externo e interno",
			"Fibras em direções opostas (cruzadas)",
			"Formam a camada muscular mais externa do core",
			"Cruciais para rotação e estabilidade",
		],
	},
	{
		id: "gluteus-medius",
		name: "Glúteo Médio",
		scientificName: "Gluteus Medius",
		group: "gluteos",
		description:
			"Músculo localizado na parte lateral do quadril, essencial para estabilização.",
		functions: [
			"Abdução do quadril (afastar a perna)",
			"Estabilização do quadril durante caminhada",
			"Rotação interna do quadril (fibras anteriores)",
			"Rotação externa do quadril (fibras posteriores)",
		],
		commonExercises: [
			"Elevação lateral de perna",
			"Clamshell",
			"Lateral walk",
			"Single leg squat",
			"Fire hydrant",
		],
		anatomyFacts: [
			"Localizado profundamente ao glúteo máximo",
			"Crucial para prevenir dor no joelho e quadril",
			"Fraqueza causa queda pélvica durante caminhada",
			"Trabalha ativamente em movimentos unilaterais",
		],
	},
	{
		id: "hamstrings",
		name: "Isquiotibiais",
		scientificName: "Biceps Femoris, Semitendinosus, Semimembranosus",
		group: "pernas",
		description:
			"Grupo de três músculos na parte posterior da coxa, essenciais para flexão do joelho.",
		functions: [
			"Flexão do joelho (dobrar a perna)",
			"Extensão do quadril (levar a perna para trás)",
			"Rotação interna e externa do joelho",
			"Desaceleração durante corrida",
		],
		commonExercises: [
			"Mesa flexora",
			"Stiff",
			"Leg curl",
			"Nordic curl",
			"RDL",
		],
		anatomyFacts: [
			"Composto por: bíceps femoral, semitendinoso e semimembranoso",
			"Todos cruzam as articulações do quadril e joelho",
			"Grupo muscular frequentemente desequilibrado",
			"Crucial para saúde dos joelhos",
		],
	},
	{
		id: "gastrocnemius",
		name: "Gastrocnêmio",
		scientificName: "Gastrocnemius",
		group: "pernas",
		description:
			"O maior músculo da panturrilha, formando a parte superior e mais visível.",
		functions: [
			"Flexão plantar (ficar na ponta dos pés)",
			"Flexão do joelho (leve)",
			"Propulsão durante caminhada e corrida",
			"Estabilização do tornozelo",
		],
		commonExercises: [
			"Panturrilha em pé",
			"Panturrilha no leg press",
			"Elevação de panturrilha",
			"Panturrilha sentado",
			"Calf raise",
		],
		anatomyFacts: [
			"Possui duas cabeças: medial e lateral",
			"Localizado superficialmente ao sóleo",
			"Mais ativo com joelho estendido",
			"Altamente responsivo ao treino",
		],
	},
	{
		id: "soleus",
		name: "Sóleo",
		scientificName: "Soleus",
		group: "pernas",
		description:
			"Músculo plano e largo localizado profundamente ao gastrocnêmio na panturrilha.",
		functions: [
			"Flexão plantar (principal função)",
			"Estabilização da perna durante caminhada",
			"Suporte venoso (bomba muscular)",
			"Postura em pé",
		],
		commonExercises: [
			"Panturrilha sentado",
			"Panturrilha no leg press",
			"Panturrilha unipodal",
			"Calf raise sentado",
		],
		anatomyFacts: [
			"Localizado profundamente ao gastrocnêmio",
			"Mais ativo com joelho flexionado",
			"Contém maior porcentagem de fibras de resistência",
			"Essencial para bomba venosa (circulação)",
		],
	},
	{
		id: "forearms",
		name: "Antebraços",
		scientificName: "Flexor & Extensor Carpi, Brachioradialis",
		group: "bracos",
		description:
			"Grupo de músculos que controlam os movimentos do punho e dedos.",
		functions: [
			"Flexão do punho",
			"Extensão do punho",
			"Pronação e supinação",
			"Fortalecimento de pegada",
		],
		commonExercises: [
			"Rosca punho",
			"Extensão de punho",
			"Martelo",
			"Farmer's walk",
			"Rolinho de punho",
		],
		anatomyFacts: [
			"Composto por mais de 20 músculos pequenos",
			"Crucial para força de pegada",
			"Trabalha em todos os exercícios de puxar",
			"Alto potencial de crescimento",
		],
	},
	{
		id: "serratus-anterior",
		name: "Serrátil Anterior",
		scientificName: "Serratus Anterior",
		group: "peito",
		description:
			"Músculo localizado nas laterais do tórax, conhecido como 'caixa torácica'.",
		functions: [
			"Protração das escápulas (empurrar para frente)",
			"Rotação superior das escápulas",
			"Estabilização das escápulas",
			"Fixação da escápula ao tórax",
		],
		commonExercises: [
			"Flexão de braço",
			"Prancha com protração",
			"Serrate press",
			"Dip",
			"Wall slide",
		],
		anatomyFacts: [
			"Forma as 'abas' visíveis nas laterais do peito",
			"Crucial para movimentos de empurrar",
			"Fraqueza causa 'asas de anjo' (escápulas destacadas)",
			"Trabalha sinergicamente com peitoral",
		],
	},
	{
		id: "teres-major",
		name: "Redondo Maior",
		scientificName: "Teres Major",
		group: "costas",
		description:
			"Músculo redondo localizado na parte inferior das costas, trabalhando com o grande dorsal.",
		functions: [
			"Adução do braço",
			"Extensão do ombro",
			"Rotação interna do ombro",
			"Estabilização do ombro",
		],
		commonExercises: [
			"Remada curvada",
			"Pulldown",
			"Pullover",
			"Remada unilateral",
			"Barra fixa",
		],
		anatomyFacts: [
			"Trabalha em conjunto com o grande dorsal",
			"Localizado próximo ao tríceps",
			"Conhecido como 'pequeno latíssimo'",
			"Crucial para força de puxar",
		],
	},
	{
		id: "infraspinatus",
		name: "Infraespinhal",
		scientificName: "Infraspinatus",
		group: "ombros",
		description:
			"Músculo do manguito rotador localizado na escápula, essencial para estabilidade do ombro.",
		functions: [
			"Rotação externa do ombro",
			"Abdução do ombro (leve)",
			"Estabilização da cabeça do úmero",
			"Proteção da articulação do ombro",
		],
		commonExercises: [
			"Rotação externa",
			"Face pull",
			"Rotação externa deitado",
			"Band pull-apart",
			"Cable external rotation",
		],
		anatomyFacts: [
			"Parte do manguito rotador",
			"Frequentemente fraco em praticantes de musculação",
			"Crucial para prevenir lesões no ombro",
			"Trabalha em antagonismo ao peitoral",
		],
	},
	{
		id: "supraspinatus",
		name: "Supraespinhal",
		scientificName: "Supraspinatus",
		group: "ombros",
		description: "Músculo do manguito rotador que inicia a abdução do braço.",
		functions: [
			"Abdução do braço (primeiros 15 graus)",
			"Estabilização do ombro",
			"Assistência na abdução total",
			"Proteção da articulação",
		],
		commonExercises: [
			"Elevação lateral",
			"Rotação interna",
			"Pendulum",
			"Empty can",
			"Prone Y",
		],
		anatomyFacts: [
			"Inicia o movimento de elevação lateral",
			"Mais comum lesão do manguito rotador",
			"Trabalha com deltoide na abdução",
			"Localizado na fossa supraespinhal da escápula",
		],
	},
	{
		id: "pectoralis-minor",
		name: "Peitoral Menor",
		scientificName: "Pectoralis Minor",
		group: "peito",
		description:
			"Músculo pequeno localizado profundamente ao peitoral maior, conectando escápula às costelas.",
		functions: [
			"Depressão das escápulas",
			"Protração das escápulas",
			"Rotação inferior das escápulas",
			"Elevação das costelas (respiração)",
		],
		commonExercises: [
			"Flexão de braço",
			"Dips",
			"Puxada",
			"Remada",
			"Pullover",
		],
		anatomyFacts: [
			"Localizado profundamente ao peitoral maior",
			"Pode causar síndrome do desfiladeiro torácico",
			"Encurtamento comum em pessoas com má postura",
			"Trabalha em movimentos de empurrar",
		],
	},
	{
		id: "transverse-abdominis",
		name: "Transverso Abdominal",
		scientificName: "Transversus Abdominis",
		group: "core",
		description:
			"Músculo mais profundo do abdômen, funcionando como um cinto natural.",
		functions: [
			"Compressão abdominal",
			"Estabilização da coluna lombar",
			"Suporte dos órgãos internos",
			"Exalação forçada",
		],
		commonExercises: [
			"Prancha",
			"Dead bug",
			"Bird dog",
			"Hollow hold",
			"Vacuum",
		],
		anatomyFacts: [
			"Músculo mais profundo do core",
			"Funciona como um cinto interno",
			"Ativo antes de qualquer movimento",
			"Crucial para estabilidade lombar",
		],
	},
	{
		id: "hip-flexors",
		name: "Flexores do Quadril",
		scientificName: "Iliopsoas, Rectus Femoris",
		group: "pernas",
		description: "Grupo de músculos que elevam a perna em direção ao tronco.",
		functions: [
			"Flexão do quadril (elevar a perna)",
			"Estabilização do quadril",
			"Assistência na extensão do joelho (reto femoral)",
			"Postura em pé",
		],
		commonExercises: [
			"Elevação de perna",
			"Leg raise",
			"Knee raise",
			"Mountain climber",
			"Hip flexor stretch",
		],
		anatomyFacts: [
			"Composto principalmente por psoas e ilíaco",
			"Frequentemente encurtado em pessoas sedentárias",
			"Crucial para corrida e chutes",
			"Trabalha constantemente na postura",
		],
	},
	{
		id: "adductors",
		name: "Adutores",
		scientificName: "Adductor Magnus, Longus, Brevis",
		group: "pernas",
		description:
			"Grupo de músculos na parte interna da coxa que aproximam as pernas.",
		functions: [
			"Adução do quadril (aproximar as pernas)",
			"Estabilização do quadril",
			"Flexão e extensão do quadril (dependendo da porção)",
			"Rotação interna",
		],
		commonExercises: [
			"Adutora na máquina",
			"Sumo squat",
			"Leg press sumo",
			"Side lunge",
			"Copenhagen plank",
		],
		anatomyFacts: [
			"Composto por adutor magno, longo e curto",
			"Frequentemente negligenciado no treino",
			"Crucial para estabilidade do quadril",
			"Trabalha em movimentos de agachamento",
		],
	},
];