import type {
  GymProfile,
  StudentData,
  Equipment,
  GymStats,
  CheckIn,
  UserProfile,
  UserProgress,
  PersonalRecord,
  MembershipPlan,
  Payment,
  Coupon,
  Referral,
  Expense,
  FinancialSummary,
  GymLocation,
  DayPass,
} from "./types"

export const mockGymProfile: GymProfile = {
  id: "gym-001",
  name: "PowerFit Academia",
  logo: "/abstract-gym-logo.png",
  address: "Rua das Flores, 123 - Centro",
  phone: "(11) 98765-4321",
  email: "contato@powerfit.com.br",
  cnpj: "12.345.678/0001-90",
  plan: "premium",
  totalStudents: 234,
  activeStudents: 187,
  equipmentCount: 45,
  createdAt: new Date("2020-01-15"),
  gamification: {
    level: 12,
    xp: 2450,
    xpToNextLevel: 500,
    currentStreak: 45,
    longestStreak: 89,
    achievements: [],
    monthlyStudentGoal: 250,
    avgStudentFrequency: 3.2,
    equipmentUtilization: 78,
    ranking: 3,
  },
}

export const mockStudents: StudentData[] = [
  {
    id: "student-001",
    name: "Carlos Silva",
    email: "carlos@email.com",
    avatar: "/male-fitness.jpg",
    age: 28,
    gender: "male",
    phone: "(11) 91234-5678",
    membershipStatus: "active",
    joinDate: new Date("2023-01-10"),
    lastVisit: new Date(),
    totalVisits: 145,
    currentStreak: 12,
    currentWeight: 82,
    attendanceRate: 85,
    favoriteEquipment: ["Supino Reto", "Leg Press", "Puxada Alta"],
    assignedTrainer: "João Personal",
    profile: {
      id: "student-001",
      name: "Carlos Silva",
      age: 28,
      gender: "male",
      height: 178,
      weight: 82,
      fitnessLevel: "intermediario",
      weeklyWorkoutFrequency: 4,
      workoutDuration: 60,
      goals: ["ganhar-massa", "forca"],
      availableEquipment: ["barra", "halteres", "supino"],
      gymType: "academia-completa",
      preferredWorkoutTime: "noite",
      preferredSets: 3,
      preferredRepRange: "hipertrofia",
      restTime: "medio",
      targetCalories: 2800,
      targetProtein: 180,
    } as UserProfile,
    progress: {
      currentStreak: 12,
      longestStreak: 25,
      totalXP: 3450,
      currentLevel: 8,
      xpToNextLevel: 550,
      workoutsCompleted: 145,
      achievements: [],
      lastActivityDate: new Date().toISOString(),
      dailyGoalXP: 50,
      weeklyXP: [40, 60, 50, 70, 45, 55, 50],
      todayXP: 50,
    } as UserProgress,
    workoutHistory: [],
    personalRecords: [
      {
        exerciseId: "bench-press",
        exerciseName: "Supino Reto",
        type: "max-weight",
        value: 100,
        date: new Date("2024-11-15"),
      },
    ] as PersonalRecord[],
    weightHistory: [
      { date: new Date("2024-09-01"), weight: 85 },
      { date: new Date("2024-10-01"), weight: 83.5 },
      { date: new Date("2024-11-01"), weight: 82 },
    ],
  } as StudentData,
  {
    id: "student-002",
    name: "Maria Santos",
    email: "maria@email.com",
    avatar: "/female-fitness.jpg",
    age: 32,
    gender: "female",
    phone: "(11) 92345-6789",
    membershipStatus: "active",
    joinDate: new Date("2023-03-15"),
    lastVisit: new Date(Date.now() - 86400000),
    totalVisits: 98,
    currentStreak: 8,
    currentWeight: 65,
    attendanceRate: 92,
    favoriteEquipment: ["Esteira", "Agachamento Livre", "Cadeira Abdutora"],
    profile: {
      id: "student-002",
      name: "Maria Santos",
      age: 32,
      gender: "female",
      height: 165,
      weight: 65,
      fitnessLevel: "intermediario",
      weeklyWorkoutFrequency: 5,
      workoutDuration: 45,
      goals: ["definir", "resistencia"],
      availableEquipment: ["esteira", "bicicleta"],
      gymType: "academia-completa",
      preferredWorkoutTime: "manha",
      preferredSets: 3,
      preferredRepRange: "hipertrofia",
      restTime: "curto",
      targetCalories: 1800,
      targetProtein: 120,
    } as UserProfile,
    progress: {
      currentStreak: 8,
      longestStreak: 18,
      totalXP: 2890,
      currentLevel: 7,
      xpToNextLevel: 350,
      workoutsCompleted: 98,
      achievements: [],
      lastActivityDate: new Date(Date.now() - 86400000).toISOString(),
      dailyGoalXP: 50,
      weeklyXP: [50, 55, 60, 50, 45, 0, 55],
      todayXP: 55,
    } as UserProgress,
    workoutHistory: [],
    personalRecords: [
      {
        exerciseId: "squat",
        exerciseName: "Agachamento",
        type: "max-weight",
        value: 80,
        date: new Date("2024-11-10"),
      },
    ] as PersonalRecord[],
    weightHistory: [
      { date: new Date("2024-09-01"), weight: 67 },
      { date: new Date("2024-10-01"), weight: 66 },
      { date: new Date("2024-11-01"), weight: 65 },
    ],
  } as StudentData,
  {
    id: "student-003",
    name: "Pedro Oliveira",
    email: "pedro@email.com",
    avatar: "/male-athlete.png",
    age: 24,
    gender: "male",
    phone: "(11) 93456-7890",
    membershipStatus: "active",
    joinDate: new Date("2022-11-20"),
    lastVisit: new Date(),
    totalVisits: 203,
    currentStreak: 25,
    currentWeight: 88,
    attendanceRate: 95,
    favoriteEquipment: ["Barra Fixa", "Agachamento Livre", "Desenvolvimento"],
    assignedTrainer: "Ana Personal",
    profile: {
      id: "student-003",
      name: "Pedro Oliveira",
      age: 24,
      gender: "male",
      height: 183,
      weight: 88,
      fitnessLevel: "avancado",
      weeklyWorkoutFrequency: 6,
      workoutDuration: 90,
      goals: ["ganhar-massa", "forca", "definir"],
      availableEquipment: ["barra", "halteres", "supino"],
      gymType: "academia-completa",
      preferredWorkoutTime: "tarde",
      preferredSets: 4,
      preferredRepRange: "hipertrofia",
      restTime: "medio",
      targetCalories: 3200,
      targetProtein: 200,
    } as UserProfile,
    progress: {
      currentStreak: 25,
      longestStreak: 45,
      totalXP: 5670,
      currentLevel: 12,
      xpToNextLevel: 780,
      workoutsCompleted: 203,
      achievements: [],
      lastActivityDate: new Date().toISOString(),
      dailyGoalXP: 50,
      weeklyXP: [70, 65, 80, 75, 70, 85, 80],
      todayXP: 80,
    } as UserProgress,
    workoutHistory: [],
    personalRecords: [
      {
        exerciseId: "bench-press",
        exerciseName: "Supino Reto",
        type: "max-weight",
        value: 120,
        date: new Date("2024-11-20"),
      },
      {
        exerciseId: "deadlift",
        exerciseName: "Levantamento Terra",
        type: "max-weight",
        value: 180,
        date: new Date("2024-11-18"),
      },
    ] as PersonalRecord[],
    weightHistory: [
      { date: new Date("2024-09-01"), weight: 85 },
      { date: new Date("2024-10-01"), weight: 86.5 },
      { date: new Date("2024-11-01"), weight: 88 },
    ],
  } as StudentData,
]

export const mockEquipment: Equipment[] = [
  {
    id: "eq-001",
    name: "Esteira Profissional 1",
    type: "cardio",
    brand: "Movement",
    model: "LX160",
    serialNumber: "EST001-2023",
    purchaseDate: new Date("2023-01-15"),
    lastMaintenance: new Date("2024-10-01"),
    nextMaintenance: new Date("2025-04-01"),
    status: "in-use",
    currentUser: {
      studentId: "student-002",
      studentName: "Maria Santos",
      startTime: new Date(Date.now() - 900000), // 15 min atrás
    },
    usageStats: {
      totalUses: 1247,
      avgUsageTime: 25,
      popularTimes: ["07:00-09:00", "18:00-20:00"],
    },
    maintenanceHistory: [],
  },
  {
    id: "eq-002",
    name: "Supino Reto",
    type: "musculacao",
    brand: "Kikos",
    model: "Pro Series",
    serialNumber: "SUP002-2022",
    purchaseDate: new Date("2022-06-10"),
    lastMaintenance: new Date("2024-11-15"),
    nextMaintenance: new Date("2025-05-15"),
    status: "available",
    usageStats: {
      totalUses: 2134,
      avgUsageTime: 18,
      popularTimes: ["18:00-21:00"],
    },
    maintenanceHistory: [],
  },
  {
    id: "eq-003",
    name: "Leg Press 45°",
    type: "musculacao",
    brand: "Kikos",
    model: "Pro Series",
    serialNumber: "LEG003-2022",
    purchaseDate: new Date("2022-06-10"),
    lastMaintenance: new Date("2024-09-20"),
    nextMaintenance: new Date("2025-03-20"),
    status: "available",
    usageStats: {
      totalUses: 1876,
      avgUsageTime: 15,
      popularTimes: ["17:00-20:00"],
    },
    maintenanceHistory: [],
  },
  {
    id: "eq-004",
    name: "Bicicleta Ergométrica 3",
    type: "cardio",
    brand: "Movement",
    model: "BK450",
    serialNumber: "BIC004-2023",
    purchaseDate: new Date("2023-03-20"),
    status: "maintenance",
    usageStats: {
      totalUses: 892,
      avgUsageTime: 30,
      popularTimes: ["06:00-08:00", "19:00-21:00"],
    },
    maintenanceHistory: [],
  },
  {
    id: "eq-005",
    name: "Puxada Alta",
    type: "musculacao",
    brand: "Kikos",
    model: "Pro Series",
    serialNumber: "PUX005-2022",
    purchaseDate: new Date("2022-06-10"),
    status: "in-use",
    currentUser: {
      studentId: "student-001",
      studentName: "Carlos Silva",
      startTime: new Date(Date.now() - 420000), // 7 min atrás
    },
    usageStats: {
      totalUses: 1998,
      avgUsageTime: 12,
      popularTimes: ["18:00-21:00"],
    },
    maintenanceHistory: [],
  },
]

export const mockGymStats: GymStats = {
  today: {
    checkins: 67,
    activeStudents: 34,
    equipmentInUse: 18,
    peakHour: "19:00",
  },
  week: {
    totalCheckins: 423,
    avgDailyCheckins: 60,
    newMembers: 5,
    canceledMembers: 2,
    revenue: 12450,
  },
  month: {
    totalCheckins: 1847,
    retentionRate: 94,
    growthRate: 8,
    topStudents: mockStudents,
    mostUsedEquipment: mockEquipment,
  },
}

export const mockRecentCheckIns: CheckIn[] = [
  {
    id: "checkin-001",
    studentId: "student-001",
    studentName: "Carlos Silva",
    timestamp: new Date(Date.now() - 1800000), // 30 min atrás
  },
  {
    id: "checkin-002",
    studentId: "student-002",
    studentName: "Maria Santos",
    timestamp: new Date(Date.now() - 3600000), // 1h atrás
  },
  {
    id: "checkin-003",
    studentId: "student-003",
    studentName: "Pedro Oliveira",
    timestamp: new Date(Date.now() - 5400000), // 1.5h atrás
  },
]

export const mockMembershipPlans: MembershipPlan[] = [
  {
    id: "plan-001",
    name: "Mensal",
    type: "monthly",
    price: 120,
    duration: 30,
    benefits: ["Acesso ilimitado", "1 avaliação física"],
    isActive: true,
  },
  {
    id: "plan-002",
    name: "Trimestral",
    type: "quarterly",
    price: 330,
    duration: 90,
    benefits: ["Acesso ilimitado", "2 avaliações físicas", "5% desconto"],
    isActive: true,
  },
  {
    id: "plan-003",
    name: "Semestral",
    type: "semi-annual",
    price: 600,
    duration: 180,
    benefits: ["Acesso ilimitado", "4 avaliações físicas", "10% desconto", "1 personal grátis"],
    isActive: true,
  },
  {
    id: "plan-004",
    name: "Anual",
    type: "annual",
    price: 1080,
    duration: 365,
    benefits: ["Acesso ilimitado", "8 avaliações físicas", "25% desconto", "3 personal grátis", "Matrícula grátis"],
    isActive: true,
  },
  {
    id: "plan-005",
    name: "Aula Experimental",
    type: "trial",
    price: 0,
    duration: 7,
    benefits: ["1 semana de acesso", "1 avaliação física"],
    isActive: true,
  },
]

export const mockPayments: Payment[] = [
  {
    id: "pay-001",
    studentId: "student-001",
    studentName: "Carlos Silva",
    planId: "plan-001",
    planName: "Mensal",
    amount: 120,
    date: new Date(),
    dueDate: new Date(Date.now() + 5 * 86400000),
    status: "paid",
    paymentMethod: "pix",
  },
  {
    id: "pay-002",
    studentId: "student-002",
    studentName: "Maria Santos",
    planId: "plan-003",
    planName: "Semestral",
    amount: 600,
    date: new Date(Date.now() - 10 * 86400000),
    dueDate: new Date(Date.now() + 20 * 86400000),
    status: "paid",
    paymentMethod: "credit-card",
  },
  {
    id: "pay-003",
    studentId: "student-003",
    studentName: "Pedro Oliveira",
    planId: "plan-002",
    planName: "Trimestral",
    amount: 330,
    date: new Date(Date.now() - 2 * 86400000),
    dueDate: new Date(Date.now() - 2 * 86400000),
    status: "overdue",
    paymentMethod: "bank-transfer",
  },
]

export const mockCoupons: Coupon[] = [
  {
    id: "coup-001",
    code: "BEMVINDO2024",
    type: "percentage",
    value: 20,
    maxUses: 50,
    currentUses: 12,
    expiryDate: new Date("2024-12-31"),
    isActive: true,
  },
  {
    id: "coup-002",
    code: "AMIGO50",
    type: "fixed",
    value: 50,
    maxUses: 100,
    currentUses: 34,
    expiryDate: new Date("2025-03-31"),
    isActive: true,
  },
]

export const mockReferrals: Referral[] = [
  {
    id: "ref-001",
    referrerId: "student-001",
    referrerName: "Carlos Silva",
    referredId: "student-004",
    referredName: "Ana Costa",
    date: new Date(Date.now() - 15 * 86400000),
    status: "completed",
    reward: 50,
  },
  {
    id: "ref-002",
    referrerId: "student-003",
    referrerName: "Pedro Oliveira",
    referredId: "student-005",
    referredName: "Lucas Ferreira",
    date: new Date(Date.now() - 5 * 86400000),
    status: "pending",
    reward: 50,
  },
]

export const mockExpenses: Expense[] = [
  {
    id: "exp-001",
    type: "utilities",
    description: "Conta de luz - Novembro",
    amount: 1850,
    date: new Date(Date.now() - 5 * 86400000),
    category: "Operacional",
  },
  {
    id: "exp-002",
    type: "maintenance",
    description: "Manutenção Esteira 1",
    amount: 450,
    date: new Date(Date.now() - 10 * 86400000),
    category: "Equipamentos",
  },
  {
    id: "exp-003",
    type: "staff",
    description: "Salários - Novembro",
    amount: 8500,
    date: new Date(Date.now() - 2 * 86400000),
    category: "Pessoal",
  },
]

export const mockFinancialSummary: FinancialSummary = {
  totalRevenue: 24580,
  totalExpenses: 12340,
  netProfit: 12240,
  monthlyRecurring: 22100,
  pendingPayments: 1650,
  overduePayments: 330,
  averageTicket: 131.5,
  churnRate: 2.3,
  revenueGrowth: 12.5,
}

export const mockGymLocations: GymLocation[] = [
  {
    id: "gym-001",
    name: "PowerFit Academia",
    logo: "/abstract-gym-logo.png",
    address: "Rua das Flores, 123 - Centro",
    coordinates: {
      lat: -23.5505,
      lng: -46.6333,
    },
    distance: 0.8,
    rating: 4.8,
    totalReviews: 234,
    plans: {
      daily: 35,
      weekly: 180,
      monthly: 120,
    },
    amenities: ["Estacionamento", "Vestiário", "Wifi", "Personal Trainer", "Ar Condicionado"],
    openNow: true,
    openingHours: {
      open: "06:00",
      close: "22:00",
    },
    isPartner: true,
  },
  {
    id: "gym-002",
    name: "FitZone Premium",
    logo: "/fitzone-gym-logo.jpg",
    address: "Av. Paulista, 1500 - Bela Vista",
    coordinates: {
      lat: -23.5629,
      lng: -46.6544,
    },
    distance: 2.3,
    rating: 4.6,
    totalReviews: 189,
    plans: {
      daily: 45,
      weekly: 220,
      monthly: 150,
    },
    amenities: ["Piscina", "Sauna", "Estacionamento", "Wifi", "Nutricionista"],
    openNow: true,
    openingHours: {
      open: "05:00",
      close: "23:00",
    },
    isPartner: true,
  },
  {
    id: "gym-003",
    name: "Strong Life Gym",
    logo: "/stronglife-gym-logo.jpg",
    address: "Rua Augusta, 890 - Jardins",
    coordinates: {
      lat: -23.5558,
      lng: -46.6614,
    },
    distance: 1.5,
    rating: 4.9,
    totalReviews: 312,
    plans: {
      daily: 40,
      weekly: 200,
      monthly: 140,
    },
    amenities: ["CrossFit", "Funcional", "Estacionamento", "Personal 24h", "Vestiário Premium"],
    openNow: true,
    openingHours: {
      open: "24h",
      close: "24h",
    },
    isPartner: true,
  },
  {
    id: "gym-004",
    name: "BodyShape Centro",
    logo: "/bodyshape-gym-logo.jpg",
    address: "Rua da Consolação, 2100 - Consolação",
    coordinates: {
      lat: -23.5489,
      lng: -46.6514,
    },
    distance: 3.1,
    rating: 4.5,
    totalReviews: 156,
    plans: {
      daily: 30,
      weekly: 150,
      monthly: 100,
    },
    amenities: ["Musculação", "Aeróbico", "Wifi", "Vestiário"],
    openNow: false,
    openingHours: {
      open: "06:00",
      close: "22:00",
    },
    isPartner: true,
  },
  {
    id: "gym-005",
    name: "Elite Fitness Club",
    logo: "/elite-fitness-logo.jpg",
    address: "Av. Rebouças, 3000 - Pinheiros",
    coordinates: {
      lat: -23.5689,
      lng: -46.6789,
    },
    distance: 4.2,
    rating: 4.7,
    totalReviews: 278,
    plans: {
      daily: 50,
      weekly: 250,
      monthly: 180,
    },
    amenities: ["Spa", "Piscina Olímpica", "Squash", "Café", "Loja", "Estacionamento VIP"],
    openNow: true,
    openingHours: {
      open: "05:00",
      close: "00:00",
    },
    isPartner: true,
  },
]

export const mockDayPasses: DayPass[] = [
  {
    id: "pass-001",
    gymId: "gym-002",
    gymName: "FitZone Premium",
    purchaseDate: new Date(Date.now() - 2 * 86400000),
    validDate: new Date(Date.now() + 3 * 86400000),
    price: 45,
    status: "active",
    qrCode: "QR_FITZONE_001",
  },
]
