import type { FunctionalExercise } from "./types";

export const functionalExercises: FunctionalExercise[] = [
	{
		id: "func-1",
		name: "Agachamento com Rotação",
		category: "mobilidade",
		description:
			"Agachamento profundo com rotação do tronco para melhorar mobilidade de quadril e coluna",
		sets: 3,
		duration: "10 reps",
		rest: 45,
		difficulty: "iniciante",
		benefits: ["Melhora mobilidade", "Fortalece core", "Previne lesões"],
		targetAudience: ["adultos", "idosos"],
		equipment: ["Peso Corporal"],
		caloriesBurnedPerMinute: 4.5,
	},
	{
		id: "func-2",
		name: "Prancha Dinâmica",
		category: "core-funcional",
		description: "Prancha com movimento alternado dos braços",
		sets: 3,
		duration: "30s",
		rest: 30,
		difficulty: "intermediario",
		benefits: ["Fortalece core", "Melhora estabilidade", "Trabalha ombros"],
		targetAudience: ["adultos"],
		equipment: ["Peso Corporal"],
		caloriesBurnedPerMinute: 6.0,
	},
	{
		id: "func-3",
		name: "Passada com Rotação",
		category: "coordenacao",
		description: "Passada frontal com rotação do tronco",
		sets: 3,
		duration: "12 reps",
		rest: 45,
		difficulty: "intermediario",
		benefits: ["Melhora equilíbrio", "Fortalece pernas", "Aumenta coordenação"],
		targetAudience: ["adultos", "criancas"],
		equipment: ["Peso Corporal"],
		caloriesBurnedPerMinute: 5.5,
	},
	{
		id: "func-4",
		name: "Bird Dog",
		category: "equilibrio",
		description: "Extensão alternada de braço e perna oposta",
		sets: 3,
		duration: "10 reps cada lado",
		rest: 30,
		difficulty: "iniciante",
		benefits: ["Melhora equilíbrio", "Fortalece lombar", "Estabiliza coluna"],
		targetAudience: ["adultos", "idosos"],
		equipment: ["Peso Corporal"],
		caloriesBurnedPerMinute: 3.5,
	},
	{
		id: "func-5",
		name: "Caminhada do Urso",
		category: "agilidade",
		description: "Caminhada em quatro apoios mantendo quadril elevado",
		sets: 3,
		duration: "20 passos",
		rest: 45,
		difficulty: "intermediario",
		benefits: [
			"Melhora coordenação",
			"Fortalece corpo todo",
			"Aumenta agilidade",
		],
		targetAudience: ["adultos", "criancas"],
		equipment: ["Peso Corporal"],
		caloriesBurnedPerMinute: 7.0,
	},
	{
		id: "func-6",
		name: "Sentar e Levantar da Cadeira",
		category: "mobilidade",
		description: "Exercício funcional para idosos praticarem movimento diário",
		sets: 3,
		duration: "12 reps",
		rest: 60,
		difficulty: "iniciante",
		benefits: ["Fortalece pernas", "Melhora independência", "Previne quedas"],
		targetAudience: ["idosos"],
		equipment: ["Cadeira"],
		caloriesBurnedPerMinute: 3.0,
	},
	{
		id: "func-7",
		name: "Marcha Estacionária Coordenada",
		category: "coordenacao",
		description: "Marcha no lugar com movimentos coordenados de braços",
		sets: 3,
		duration: "60s",
		rest: 30,
		difficulty: "iniciante",
		benefits: [
			"Melhora coordenação motora",
			"Aquece corpo",
			"Desenvolve ritmo",
		],
		targetAudience: ["criancas", "idosos"],
		equipment: ["Peso Corporal"],
		caloriesBurnedPerMinute: 4.0,
	},
	{
		id: "func-8",
		name: "Equilíbrio em Uma Perna",
		category: "equilibrio",
		description: "Exercício de equilíbrio estático e dinâmico",
		sets: 3,
		duration: "30s cada perna",
		rest: 30,
		difficulty: "iniciante",
		benefits: [
			"Previne quedas",
			"Fortalece tornozelos",
			"Melhora propriocepção",
		],
		targetAudience: ["adultos", "idosos"],
		equipment: ["Peso Corporal"],
		caloriesBurnedPerMinute: 2.8,
	},
	{
		id: "func-9",
		name: "Polichinelos Modificados",
		category: "agilidade",
		description: "Polichinelos com impacto reduzido para todas as idades",
		sets: 3,
		duration: "30s",
		rest: 30,
		difficulty: "iniciante",
		benefits: [
			"Melhora condicionamento",
			"Aquece corpo",
			"Desenvolve coordenação",
		],
		targetAudience: ["criancas", "adultos", "idosos"],
		equipment: ["Peso Corporal"],
		caloriesBurnedPerMinute: 5.0,
	},
	{
		id: "func-10",
		name: "Rotação de Tronco com Bola",
		category: "core-funcional",
		description: "Rotações controladas segurando uma bola medicinal",
		sets: 3,
		duration: "15 reps",
		rest: 45,
		difficulty: "intermediario",
		benefits: ["Fortalece oblíquos", "Melhora rotação", "Aumenta potência"],
		targetAudience: ["adultos"],
		equipment: ["Bola Medicinal"],
		caloriesBurnedPerMinute: 5.5,
	},
];
